extends TestCase
## CAD road (scenes/tracks/rbr_road.tscn, generated by cad/track/road.py).

const TRACK_SCENE := "res://scenes/tracks/red_bull_ring.tscn"
const RACE_SCENE := "res://scenes/race_red_bull_ring.tscn"

## Casts straight down at `at` and returns the first hit on a body that belongs to the road
## (other track units may put kerbs or scenery on top; those are skipped).
func _road_hit(road: Node3D, at: Vector3) -> Dictionary:
	var space := road.get_world_3d().direct_space_state
	var q := PhysicsRayQueryParameters3D.create(at + Vector3.UP * 20.0, at + Vector3.DOWN * 20.0)
	var exclude: Array[RID] = []
	for attempt in 8:
		q.exclude = exclude
		var hit := space.intersect_ray(q)
		if hit.is_empty():
			return hit
		var col := hit["collider"] as Node
		if col != null and road.is_ancestor_of(col):
			return hit
		exclude.append(hit["rid"])
	return {}

func _road_of(scene: Node) -> RoadSurface:
	return scene.get_node("Road") as RoadSurface

func test_profile_matches_track() -> void:
	var track := spawn(TRACK_SCENE) as Track
	var road := _road_of(track)
	assert_true(road != null, "Road slot is a RoadSurface")
	if road == null:
		return
	var n := track.data.points.size()
	assert_true(road.widths.size() == n and road.banks.size() == n, "profile has one entry per point")
	var lo := INF
	var hi := -INF
	for i in n:
		lo = minf(lo, road.widths[i])
		hi = maxf(hi, road.widths[i])
		assert_true(absf(road.banks[i]) <= 0.0301, "bank within +/-3 %% at point %d" % i)
	assert_between(lo, 12.0, 13.5, "narrowest road width (m)")
	assert_between(hi, 15.0, 17.0, "widest road width (m)")
	assert_between(road.half_width_at(track.data.start_s) * 2.0, 14.9, 15.1, "grid width (m)")
	var bodies := road.find_children("*", "StaticBody3D", true, false)
	assert_between(bodies.size(), 40.0, 80.0, "chunk collision bodies (road + verge per chunk)")
	var kinds := {}
	for b: Node in bodies:
		kinds[b.get_meta("surface", "")] = true
	assert_true(kinds.has("asphalt") and kinds.has("grass"), "asphalt and grass bodies: %s" % [kinds.keys()])
	track.queue_free()

func test_surface_matches_profile() -> void:
	var track := spawn(TRACK_SCENE) as Track
	await physics_frames(2)
	var road := _road_of(track)
	var rng := RandomNumberGenerator.new()
	rng.seed = 4318
	var worst := 0.0
	var misses := 0
	for k in 50:
		var s := rng.randf() * track.data.length
		var hw := road.half_width_at(s)
		for lat: float in [0.0, -(hw - 0.5), hw - 0.5]:
			var want := road.surface_point(s, lat)
			var hit := _road_hit(road, want)
			if hit.is_empty():
				misses += 1
				continue
			var err := absf((hit["position"] as Vector3).y - want.y)
			worst = maxf(worst, err)
			assert_true(err < 0.05, "road surface at s=%.1f lat=%.1f off by %.3f m" % [s, lat, err])
			assert_true((hit["collider"] as Node).get_meta("surface", "") == "asphalt",
				"asphalt at s=%.1f lat=%.1f" % [s, lat])
		# Centreline height is the track.json centreline (banking pivots about it).
		assert_true(absf(road.surface_point(s, 0.0).y - track.data.position_at(s).y) < 0.001,
			"centreline height at s=%.1f" % s)
		# Verge: grass, no step at the road edge, outer edge at most 0.25 m below the road edge.
		for side: float in [-1.0, 1.0]:
			var ext := road.verge_at(s, side)
			var edge := road.surface_point(s, side * hw)
			if ext > 2.0:
				var mid := road.surface_point(s, side * (hw + ext * 0.5))
				var vh := _road_hit(road, mid)
				assert_true(not vh.is_empty() and (vh["collider"] as Node).get_meta("surface", "") == "grass",
					"grass verge at s=%.1f side %+.0f" % [s, side])
				var outer := road.surface_point(s, side * (hw + ext))
				assert_between(edge.y - outer.y, -0.001, 0.2501, "verge drop at s=%.1f" % s)
			var inside := _road_hit(road, road.surface_point(s, side * (hw - 0.02)))
			var outside := _road_hit(road, road.surface_point(s, side * (hw + 0.02)))
			if not inside.is_empty() and not outside.is_empty():
				var step := absf((inside["position"] as Vector3).y - (outside["position"] as Vector3).y)
				assert_true(step < 0.01, "no step at the road edge (s=%.1f, %.3f m)" % [s, step])
	assert_true(misses == 0, "%d raycasts missed the road" % misses)
	print("    road surface max error %.4f m" % worst)
	track.queue_free()

func test_chunks_are_continuous() -> void:
	var track := spawn(TRACK_SCENE) as Track
	await physics_frames(2)
	var road := _road_of(track)
	assert_true(road.chunk_ranges.size() >= 20 and road.chunk_ranges.size() <= 40, "20-40 chunks")
	for c: Array in road.chunk_ranges:
		var s := float(c[0]) * track.data.step
		var hw := road.half_width_at(s)
		for lat: float in [-(hw - 0.3), -hw * 0.5, 0.0, hw * 0.5, hw - 0.3]:
			var hs: Array[float] = []
			for ds: float in [-0.05, 0.0, 0.05]:
				var hit := _road_hit(road, road.surface_point(s + ds, lat))
				assert_true(not hit.is_empty(), "gap at chunk boundary s=%.1f lat=%.1f ds=%.2f" % [s, lat, ds])
				if not hit.is_empty():
					hs.append((hit["position"] as Vector3).y)
			if hs.size() == 3:
				assert_true(absf(hs[0] - hs[1]) < 0.02 and absf(hs[2] - hs[1]) < 0.02,
					"step at chunk boundary s=%.1f lat=%.1f: %s" % [s, lat, hs])
	track.queue_free()

func test_car_settles_on_grid() -> void:
	var scene := spawn(RACE_SCENE)
	var car := scene.get_node("Car") as Car
	car.set_input_override(0.0, 0.0, 0.0)  # hands off (holding the brake engages reverse)
	await physics_frames(480)
	var track := scene.get_node("Track") as Track
	var road := _road_of(track)
	var s := track.data.closest_s(car.global_position)
	var lat := track.data.lateral_offset(car.global_position, s)
	assert_true(absf(track.data.delta_s(track.data.start_s - 8.0, s)) < 2.0, "car on its grid slot (s=%.1f)" % s)
	assert_true(absf(lat) < road.half_width_at(s) - 1.0, "car on the tarmac (lat=%.2f)" % lat)
	var surf := road.surface_point(s, lat)
	assert_between(car.global_position.y - surf.y, 0.25, 0.5, "car resting on the road surface")
	assert_true(car.linear_velocity.length() < 0.5, "car at rest (v=%.2f)" % car.linear_velocity.length())
	var grounded := 0
	for w: WheelState in car.wheels:
		if w.contact:
			grounded += 1
	assert_true(grounded == 4, "all four wheels on the road (%d)" % grounded)
	car.clear_input_override()
	scene.queue_free()

func test_corner_insides_have_no_holes() -> void:
	var track := spawn(TRACK_SCENE) as Track
	await physics_frames(2)
	var road := _road_of(track)
	for turn: Dictionary in track.data.turns:
		var s := float(turn["s_apex"])
		var side := 1.0 if turn["direction"] == "right" else -1.0
		var hw := road.half_width_at(s)
		for d: float in [1.0, 4.0, 8.0]:
			var p := road.surface_point(s, side * (hw + d))
			var hit := _road_hit(road, p)
			assert_true(not hit.is_empty(), "%s: hole %.0f m inside the apex" % [turn["id"], d])
			if not hit.is_empty():
				assert_true((hit["collider"] as Node).get_meta("surface", "") == "grass",
					"%s: grass inside the apex" % turn["id"])
				# The infield spans the corner, so it follows the slope across it rather than the
				# extrapolated verge plane of one cross-section.
				assert_between((hit["position"] as Vector3).y - p.y, -0.75, 0.75, "%s infield height" % turn["id"])
	track.queue_free()
