"""Baku City Circuit: what the map does not have, as rebuildable data.

Two outputs, both made from the built track (track.json, road_profile.json, terrain) and the
committed OpenStreetMap cache of the surroundings step:

  --recipe   rewrites the generated block at the end of tools/track/tracks/baku.toml: building
             heights, the race-weekend grandstands and screens, and the lawns and groves of the
             parks (see GREEN below for why they are repeated there).
  (default)  writes assets/tracks/baku/landmarks/*.glb and landmarks.json: the pit building, the
             start gantry, the Flame Towers, the TV tower, and one world-space model
             (`trackside`) with the old city wall, the Maiden Tower, the street trees, the
             advertising boards and the screen frames.

Order after a change of the centreline or the road widths (all from fun-racer/):

  .venv/bin/python tools/track/build_track.py baku --offline --steps centreline,road,terrain,info
  .venv/bin/python tools/track/landmarks/baku.py --recipe
  .venv/bin/python tools/track/build_track.py baku --offline --steps surroundings
  .venv/bin/python tools/track/landmarks/baku.py
  tools/bin/godot --headless --path . --import

Sources. Positions of streets, buildings, parks, trees and the fortress wall: OpenStreetMap
(the cache in assets/tracks/baku/raw, ODbL). Grandstand names and where they stand: the
organiser's grandstand map as described by the ticket guides (grandprixgrandtours.com,
f1destinations.com, headout.com): Absheron opposite the pit building, Azneft outside Turn 16
and Philarmoniya inside it, Giz Galasi at the kink by the Maiden Tower, Mugham, Bulvar, Khazar
and Sahil along the shared stretch of Neftchilar Avenue. Their footprints, heights and exact
positions are ESTIMATES (temporary scaffolding stands, not on any map). Dimensions of the
monuments: Maiden Tower 29.5 m high and 16.5 m across, Flame Towers 182 / 165 / 161 m (OSM
`height`; en.wikipedia.org/wiki/Flame_Towers), Baku TV Tower 310 m (en.wikipedia.org/wiki/
Baku_TV_Tower), fortress walls 8 to 10 m (en.wikipedia.org/wiki/Old_City_(Baku)). Colours:
photographs on Wikimedia Commons (Category:Azerbaijan Grand Prix; "Four Seasons Hotel Baku
during 2019 Formula-1 Azerbaijan Grand Prix.jpg" for Turn 16).
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "tools" / "track"))
sys.path.insert(0, str(ROOT / "cad" / "track"))

from lib import geom, surroundings as su   # noqa: E402
import scenery_glb as sg                   # noqa: E402

ID = "baku"
OUT = ROOT / "assets" / "tracks" / ID
RECIPE = ROOT / "tools" / "track" / "tracks" / f"{ID}.toml"
BEGIN = "# >>> generated by tools/track/landmarks/baku.py --recipe: edit the tables there, not here\n"
END = "# <<< generated\n"

# Linear vertex tints (the scenery materials multiply them into white).
SANDSTONE = (0.62, 0.50, 0.34, 0.0)      # Absheron limestone of the walls and the Maiden Tower
SANDSTONE_DARK = (0.50, 0.40, 0.27, 0.0)
WHITE = (0.85, 0.85, 0.83, 0.0)
STEEL = (0.45, 0.47, 0.50, 0.0)
DARK = (0.05, 0.05, 0.06, 0.0)
TRUNK = (0.16, 0.11, 0.07, 0.0)
LEAF = [(0.035, 0.085, 0.02, 0.0), (0.05, 0.105, 0.025, 0.0), (0.065, 0.125, 0.03, 0.0)]
PINE = [(0.02, 0.055, 0.02, 0.0), (0.03, 0.07, 0.025, 0.0)]
# Advertising boards on the debris fences: plain colour fields, no real marks.
BOARDS = [(0.02, 0.22, 0.10, 0.0), (0.60, 0.02, 0.03, 0.0), (0.80, 0.80, 0.78, 0.0), (0.02, 0.10, 0.36, 0.0),
          (0.75, 0.42, 0.02, 0.0), (0.03, 0.03, 0.04, 0.0)]

# ---- tables ------------------------------------------------------------------------------
# Heights of the buildings a driver sees, where OpenStreetMap has no levels or too few
# (scenery.json "default_heights" lists them). metres; all ESTIMATES from the usual storey
# heights of the street (the oil-boom and Stalin-era blocks have 4 m floors) unless a source
# is given.
HEIGHTS = [
    # Neftchilar Avenue, city side of the main straight
    ("way/152809510", 42.0, "Government House: 10 storeys plus the corner towers"),
    ("way/152192792", 95.0, "Hilton Baku: 25 storeys"),
    ("way/152192676", 36.0, "Park Inn"),
    ("way/715443020", 24.0, ""), ("way/715443022", 24.0, ""), ("way/715443018", 24.0, ""),
    ("way/715443019", 24.0, ""),
    ("relation/2249851", 24.0, "State Border Service"),
    ("way/465973259", 22.0, ""), ("way/465973260", 22.0, ""), ("way/465973261", 22.0, ""),
    ("way/152192129", 24.0, "the long apartment block before the pits"),
    ("way/152192127", 18.0, ""),
    ("way/152192493", 26.0, "Park Bulvar mall"),
    # Pushkin and Khagani Street
    ("way/286018683", 22.0, ""), ("way/286018684", 22.0, ""), ("way/286018697", 20.0, ""),
    ("way/286017124", 20.0, ""), ("way/200195779", 16.0, "the old mill"),
    ("way/200195781", 60.0, "Landmark I office tower"), ("way/286017123", 40.0, "Landmark II"),
    ("way/172754961", 19.0, ""), ("way/172754962", 19.0, ""), ("way/172754963", 19.0, ""),
    ("way/172754964", 19.0, ""), ("way/172754965", 19.0, ""), ("way/172754966", 19.0, ""),
    ("way/172754967", 19.0, ""), ("way/488696632", 19.0, ""), ("way/488696633", 19.0, ""),
    ("way/488696634", 19.0, ""), ("way/488696641", 19.0, ""), ("way/286018688", 19.0, ""),
    # Bulbul Avenue and Zarifa Aliyeva Street
    ("relation/3793153", 22.0, ""), ("way/286020271", 22.0, ""), ("relation/3793136", 22.0, ""),
    ("relation/3793138", 22.0, ""), ("way/469204315", 40.0, "InterContinental"),
    ("way/286018695", 18.0, ""), ("way/1415213873", 18.0, ""), ("way/249200550", 20.0, ""),
    ("way/152192176", 22.0, ""), ("way/152192175", 22.0, "Maritime Academy"),
    ("way/286018698", 18.0, ""), ("way/179114290", 16.0, ""), ("way/179114297", 16.0, ""),
    ("way/1415514946", 16.0, ""), ("way/384285796", 16.0, ""), ("way/25359715", 22.0, "Museum Centre"),
    # Neftchilar Avenue, Turn 6 to Turn 7
    ("way/152191870", 20.0, ""), ("way/467246403", 16.0, ""), ("way/467246402", 14.0, ""),
    ("way/467246404", 18.0, ""), ("way/467246405", 18.0, ""),
    # Aziz Aliyev Street and the castle section
    ("way/152191393", 18.0, ""), ("way/299424044", 20.0, ""), ("way/299424043", 18.0, ""),
    ("relation/2072750", 20.0, ""), ("way/133847240", 16.0, ""), ("way/133847239", 18.0, ""),
    ("way/327765450", 12.0, ""), ("way/1335110601", 14.0, ""), ("way/299424046", 16.0, ""),
    ("way/133641453", 16.0, ""), ("way/133641457", 20.0, "Constitutional Court"),
    ("way/133641456", 16.0, ""),
    # Istiglaliyyat Street
    ("way/211461712", 20.0, ""), ("relation/2877790", 14.0, ""), ("way/153876715", 22.0, "Ismailiyya Palace"),
    ("way/153876684", 20.0, "Institute of Manuscripts"), ("way/217366428", 14.0, ""),
    ("relation/2877792", 14.0, ""), ("relation/2877793", 16.0, ""), ("way/217366429", 16.0, ""),
    ("way/152110144", 24.0, "University of Economics"), ("relation/2877791", 20.0, ""),
    ("way/217364413", 16.0, ""), ("way/153876698", 28.0, "City Hall, with its tower"),
    ("way/217364414", 18.0, ""), ("way/196291854", 30.0, ""), ("way/196291859", 30.0, ""),
    ("way/196291853", 18.0, ""), ("relation/2638273", 22.0, ""), ("way/196291852", 18.0, ""),
    ("way/196291860", 22.0, ""), ("way/152190848", 16.0, "Philharmonic Hall"),
    # Niyazi Street and Azneft Square
    ("way/152110152", 16.0, ""), ("relation/3977156", 16.0, ""), ("way/133160753", 22.0, ""),
    ("way/133160748", 34.0, "Heydar Aliyev Foundation"), ("way/133160749", 26.0, "SOCAR offices"),
    ("way/152190583", 38.0, "Four Seasons: 9 storeys under a mansard roof"),
    # Neftchilar Avenue from Azneft Square to the Maiden Tower
    ("way/279589354", 22.0, ""), ("way/152191287", 22.0, ""), ("way/465003806", 22.0, ""),
    ("way/152191301", 22.0, ""), ("way/152191309", 20.0, ""), ("way/152191374", 18.0, ""),
    ("way/464944957", 18.0, ""), ("way/152184311", 16.0, "Puppet Theatre"),
]

# Map features that are replaced by a model, or that are not there on a race weekend.
EXCLUDE = [
    ("way/822375068", "the pit building (mapped as a carport): landmarks/pit_building.glb"),
    ("way/822375069", "its annex: part of the same model"),
    ("way/1502989778", "the fortress wall of the castle section (mapped as a building with windows)"),
    ("way/1502989779", "the fortress wall behind the garden"),
    ("way/299418016", "the Maiden Tower: a stone drum without windows, in landmarks/trackside.glb"),
    ("way/418164347", "its building part"),
    ("way/253081850", "Flame Tower 1: landmarks/flame_towers.glb"),
    ("way/253082095", "Flame Tower 2"),
    ("way/253081914", "Flame Tower 3"),
]

# Grandstands: (name, s from, s to, side (+1 right, -1 left), metres from the road edge to the
# front row, depth, height). All uncovered scaffolding stands with pastel seats.
STANDS = [
    ("Absheron A", 14.0, 58.0, 1, 9.0, 20.0, 13.0),
    ("Absheron B", 64.0, 108.0, 1, 9.0, 20.0, 13.0),
    ("Absheron C", 114.0, 158.0, 1, 9.0, 20.0, 13.0),
    ("Absheron D", 164.0, 208.0, 1, 9.0, 20.0, 13.0),
    ("Absheron E", 214.0, 258.0, 1, 9.0, 20.0, 13.0),
    ("Khazar", 2296.0, 2344.0, 1, 5.5, 11.0, 8.0),
    ("Sahil", 2446.0, 2500.0, 1, 5.5, 14.0, 9.0),
    ("Philarmoniya", 4046.0, 4092.0, -1, 6.0, 10.0, 7.0),
    ("Azneft", 4136.0, 4214.0, 1, 13.0, 18.0, 12.0),
    ("Giz Galasi", 4636.0, 4700.0, 1, 8.0, 16.0, 11.0),
    ("Mugham", 4806.0, 4866.0, 1, 8.0, 16.0, 11.0),
    ("Bulvar", 4914.0, 4974.0, 1, 8.0, 14.0, 10.0),
]

# Big screens: (s, side, metres from the road edge, width). The frame is in trackside.glb.
SCREENS = [(4150.0, -1, 6.5, 11.0), (4668.0, -1, 5.0, 9.0)]

# Rows of street trees the map does not have: (s from, s to, side, metres from the road edge,
# spacing, species). Planes on the pavements, pines and olives along the boulevard.
TREE_ROWS = [
    (352.0, 630.0, -1, 5.5, 10.0, "plane"), (352.0, 630.0, 1, 5.5, 10.0, "plane"),
    (700.0, 1500.0, -1, 4.8, 9.0, "plane"), (700.0, 1500.0, 1, 4.8, 9.0, "plane"),
    (1570.0, 1725.0, -1, 5.0, 9.0, "plane"), (1570.0, 1725.0, 1, 5.0, 9.0, "plane"),
    (1800.0, 2045.0, -1, 5.0, 9.0, "plane"), (1800.0, 2045.0, 1, 5.0, 9.0, "plane"),
    (2185.0, 2515.0, 1, 4.8, 9.0, "plane"),
    (3035.0, 3270.0, -1, 5.5, 10.0, "plane"), (3035.0, 3270.0, 1, 5.5, 10.0, "plane"),
    (3360.0, 3740.0, -1, 5.5, 9.0, "plane"), (3360.0, 3740.0, 1, 5.5, 10.0, "plane"),
    (3800.0, 4040.0, -1, 5.0, 8.0, "plane"), (3800.0, 4080.0, 1, 5.0, 10.0, "plane"),
    (4230.0, 4700.0, -1, 5.0, 10.0, "plane"), (4230.0, 5990.0, 1, 5.5, 9.0, "boulevard"),
    (5100.0, 5880.0, -1, 5.0, 10.0, "plane"),
    (4230.0, 5990.0, 1, 15.0, 14.0, "boulevard"),
    (280.0, 330.0, 1, 18.0, 12.0, "boulevard"),
]

# Advertising boards on the fence: (s from, s to, side). They stand 3.4 m from the road edge,
# just behind the wall, so none where the wall stands back behind an escape area (the outside
# of Turns 1, 3 and 16: RUNOFF in scripts/track/trackside_layouts/baku.gd).
BOARD_RUNS = [(5700.0, 240.0, 1), (5990.0, 300.0, -1), (4260.0, 4330.0, 1), (4600.0, 5000.0, 1),
              (640.0, 700.0, 1), (2530.0, 2580.0, -1), (3740.0, 3800.0, 1),
              (2040.0, 2180.0, 1), (1740.0, 1790.0, -1)]

FLAME_TOWERS = [  # (osm way, height m): the centre and the size come from the footprint
    ("way/253081850", 181.8), ("way/253082095", 164.6), ("way/253081914", 160.8)]
TV_TOWER = (40.35153, 49.81362, 310.0)   # lat, lon (en.wikipedia.org/wiki/Baku_TV_Tower), height


# ---- the track ---------------------------------------------------------------------------
class Lap:
    def __init__(self):
        self.track = json.loads((OUT / "track.json").read_text())
        self.profile = json.loads((OUT / "road_profile.json").read_text())
        self.terrain = json.loads((OUT / "terrain.json").read_text())
        self.proj = geom.Projection(self.track["origin_latlon"][0], self.track["origin_latlon"][1],
                                    float(self.terrain["plan_scale"]))
        self.ground = su.Ground(str(OUT))
        self.corridor = su.Corridor(self.track, {
            "width": self.profile["width"], "bank": self.profile["bank"],
            "verge_left": self.profile["verge_left"], "verge_right": self.profile["verge_right"]})
        c = self.corridor
        self.n, self.step, self.length = c.n, c.step, float(self.track["length"])
        cache = sorted((OUT / "raw").glob("surroundings_near_*.json"))
        if not cache:
            raise SystemExit("no surroundings cache in assets/tracks/baku/raw")
        self.feats, _ = su.load_features(cache[0].read_text(), self.proj)
        far = sorted((OUT / "raw").glob("surroundings_far_*.json"))
        self.far_feats = su.load_features(far[0].read_text(), self.proj)[0] if far else []
        self.buildings = [f for f in self.feats if f.outers and ("building" in f.tags or "building:part" in f.tags)]

    def index(self, s):
        return int(round((s % self.length) / self.step)) % self.n

    def point(self, s, side=0.0, from_edge=0.0):
        """(x, y, z) at lap distance s, `from_edge` metres beyond the road edge on `side`."""
        c, i = self.corridor, self.index(s)
        off = side * (c.half[i] + from_edge) if side else 0.0
        xz = c.xz[i] + c.right[i] * off
        return np.array([xz[0], c.y[i], xz[1]])

    def stretch(self, s0, s1, spacing):
        """Lap distances from s0 to s1 (may wrap) every `spacing` metres, both ends included."""
        span = (s1 - s0) % self.length
        k = max(1, int(round(span / spacing)))
        return [(s0 + span * j / k) % self.length for j in range(k + 1)]

    def band(self, s0, s1, side, d0, d1, spacing=24.0):
        """Ring (x, z) of the strip between d0 and d1 metres beyond the road edge."""
        ss = self.stretch(s0, s1, spacing)
        inner = [self.point(s, side, d0)[[0, 2]] for s in ss]
        outer = [self.point(s, side, d1)[[0, 2]] for s in ss]
        return su.simplify(np.array(inner + outer[::-1]), 0.3, closed=True)

    def latlon(self, ring):
        lat, lon = self.proj.to_latlon(np.asarray(ring)[:, 0], np.asarray(ring)[:, 1])
        return [[round(float(a), 6), round(float(b), 6)] for a, b in zip(lat, lon)]

    def feature(self, ref):
        for f in self.feats + self.far_feats:
            if f.ref == ref and f.outers:
                return f
        raise SystemExit(f"{ref} is not in the surroundings cache")


def in_any(pt, rings):
    return bool(rings) and bool(su.points_in_rings(np.asarray(pt, dtype=np.float64)[None], rings)[0])


# ---- the recipe block --------------------------------------------------------------------
def green_areas(lap, reach=400.0):
    """(kind, ring) of the mapped lawns and groves within `reach` of the lap, big ones first.

    The land-cover class "grass" is also what the map leaves blank, and in the middle of Baku
    blank means paving stones and dusty yards, so environment.json colours that class as
    ground. The real lawns are therefore painted again as "farmland" (coloured as watered
    lawn there) and the groves as "forest" on top of them, in the map's own order."""
    out = []
    for f in lap.feats:
        if not f.outers or "building" in f.tags or "building:part" in f.tags:
            continue
        c = su.land_class(f.tags)
        if c is None or c[0] not in (su.GRASS, su.FOREST):
            continue
        for ring in f.outers:
            if float(lap.corridor.nearest(ring)[2].min()) > reach:
                continue
            ring = su.simplify(ring, 1.5, closed=True)
            area = abs(sg.signed_area(ring))
            if len(ring) >= 3 and area >= 60.0:
                out.append((area, "farmland" if c[0] == su.GRASS else "forest", ring, f.ref))
    out.sort(key=lambda e: -e[0])
    return out


def recipe_block(lap):
    lines = [BEGIN, "[surroundings]\n",
             "# Groves of the boulevard and the gardens: planted, not woodland.\n",
             "tree_density = 90\n", 'tree_species = "broadleaved"\n', "\n"]
    for ref, why in EXCLUDE:
        lines += [f"[[surroundings.exclude]]    # {why}\n", f'osm = "{ref}"\n']
    lines.append("\n")
    for ref, height, why in HEIGHTS:
        note = f"    # {why}" if why else ""
        lines += ["[[surroundings.building]]\n", f'osm = "{ref}"\n', f"height = {height}{note}\n"]
    lines.append("\n# Lawns (farmland) and groves (forest) of the parks: see green_areas() in the generator.\n")
    for _, kind, ring, ref in green_areas(lap):
        lines += [f"[[surroundings.add]]    # {ref}\n", f'kind = "{kind}"\n',
                  f"polygon = {json.dumps(lap.latlon(ring))}\n"]
    lines.append("\n# Race-weekend grandstands (estimated footprints, see the generator).\n")
    for name, s0, s1, side, d0, depth, height in STANDS:
        ring = lap.band(s0, s1, side, d0, d0 + depth)
        lines += [f"[[surroundings.add]]    # {name}: s = {s0:.0f} to {s1:.0f}, {'right' if side > 0 else 'left'}\n",
                  'kind = "grandstand"\n', f"height = {height}\n", f"polygon = {json.dumps(lap.latlon(ring))}\n"]
    lines.append("\n# Big screens facing the stands.\n")
    for s, side, d, width in SCREENS:
        ring = lap.band(s - 0.5 * width, s + 0.5 * width, side, d, d + 0.5, spacing=width)
        lines += [f"[[surroundings.add]]    # s = {s:.0f}\n", 'kind = "screen"\n', "min_height = 4.5\n",
                  "height = 10.5\n", f"polygon = {json.dumps(lap.latlon(ring))}\n"]
    lines.append(END)
    return lines


def write_recipe(lap):
    text = RECIPE.read_text()
    if BEGIN in text:
        text = text[:text.index(BEGIN)] + text[text.index(END) + len(END):]
    text = text.rstrip("\n") + "\n\n" + "".join(recipe_block(lap))
    RECIPE.write_text(text)
    print(f"recipe: {len(HEIGHTS)} heights, {len(green_areas(lap))} green areas, {len(STANDS)} stands -> {RECIPE}")


# ---- mesh helpers ------------------------------------------------------------------------
def loft(mesh, material, rings, colour, cap_top=True, cap_bottom=False):
    """Faces between successive rings (each (k, 3), same k), flat shaded, facing outward."""
    rings = [np.asarray(r, dtype=np.float64) for r in rings]
    axis = np.array([r.mean(axis=0) for r in rings])
    for a, b, ca, cb in zip(rings[:-1], rings[1:], axis[:-1], axis[1:]):
        k = len(a)
        centre = 0.5 * (ca + cb)
        for j in range(k):
            quad = [a[j], a[(j + 1) % k], b[(j + 1) % k], b[j]]
            if np.linalg.norm(b[j] - b[(j + 1) % k]) < 1e-6:
                quad = quad[:3]
            mesh.face(material, quad, None, colour, float(rings[0][:, 1].min()), away_from=centre)
    if cap_top and np.ptp(rings[-1], axis=0).max() > 1e-6:
        mesh.face(material, rings[-1], (0.0, 1.0, 0.0), colour)
    if cap_bottom:
        mesh.face(material, rings[0], (0.0, -1.0, 0.0), colour)


def circle(cx, y, cz, rx, rz=None, sides=6, turn=0.0):
    rz = rx if rz is None else rz
    a = turn + np.arange(sides) * (2.0 * math.pi / sides)
    return np.stack([cx + rx * np.cos(a), np.full(sides, y), cz + rz * np.sin(a)], axis=1)


def oriented_box(mesh, material, centre, along, half_len, half_wid, y0, y1, colour):
    """Box with its long side along the plan direction `along` (unit (x, z))."""
    a = np.asarray(along, dtype=np.float64)
    r = np.array([-a[1], a[0]])
    c = np.asarray(centre, dtype=np.float64)
    corners = [c + a * sa * half_len + r * sr * half_wid for sa, sr in ((-1, -1), (1, -1), (1, 1), (-1, 1))]
    low = np.array([[p[0], y0, p[1]] for p in corners])
    high = np.array([[p[0], y1, p[1]] for p in corners])
    loft(mesh, material, [low, high], colour, cap_top=True, cap_bottom=True)


def tree(mesh, x, y, z, height, kind, rng):
    """One low-poly tree (15 to 35 triangles), drawn with the plain tinted roof material."""
    y -= 0.3
    turn = rng.uniform(0.0, math.pi)
    if kind == "cypress":
        loft(mesh, "building_roof", [circle(x, y, z, 0.18, sides=3), circle(x, y + 0.15 * height, z, 0.18, sides=3)],
             TRUNK, cap_top=False)
        r = 0.11 * height
        loft(mesh, "building_roof", [circle(x, y + 0.12 * height, z, 0.6 * r, sides=5, turn=turn),
                                     circle(x, y + 0.40 * height, z, r, sides=5, turn=turn),
                                     circle(x, y + height, z, 0.02, sides=5, turn=turn)],
             PINE[int(rng.integers(len(PINE)))], cap_top=False)
        return
    if kind == "palm":
        loft(mesh, "building_roof", [circle(x, y, z, 0.3, sides=3), circle(x, y + 0.82 * height, z, 0.22, sides=3)],
             TRUNK, cap_top=False)
        top = np.array([x, y + 0.86 * height, z])
        col = LEAF[int(rng.integers(len(LEAF)))]
        for j in range(5):
            a = turn + j * 2.0 * math.pi / 5.0
            d = np.array([math.cos(a), 0.0, math.sin(a)])
            w = np.array([-d[2], 0.0, d[0]]) * 0.55
            mid = top + d * 0.28 * height + np.array([0.0, 0.05 * height, 0.0])
            tip = top + d * 0.42 * height - np.array([0.0, 0.10 * height, 0.0])
            for quad in ([top - w * 0.3, top + w * 0.3, mid + w, mid - w], [mid - w, mid + w, tip]):
                mesh.face("building_roof", quad, (0.0, 1.0, 0.0), col)
                mesh.face("building_roof", quad[::-1], (0.0, -1.0, 0.0), col)
        return
    pine = kind == "pine"
    bole = (0.55 if pine else 0.36) * height
    loft(mesh, "building_roof", [circle(x, y, z, 0.26, sides=3), circle(x, y + bole + 0.1 * height, z, 0.18, sides=3)],
         TRUNK, cap_top=False)
    r = (0.30 if pine else 0.27) * height
    col = (PINE if pine else LEAF)[int(rng.integers(len(PINE if pine else LEAF)))]
    if pine:    # the umbrella crown of the Eldar pines of the boulevard
        levels = [(bole, 0.5), (bole + 0.35 * (height - bole), 1.0), (height, 0.25)]
    else:       # the round crown of a plane tree
        levels = [(bole, 0.4), (bole + 0.3 * (height - bole), 1.0), (bole + 0.72 * (height - bole), 0.85),
                  (height, 0.2)]
    rings = [circle(x + rng.uniform(-0.25, 0.25), y + h, z + rng.uniform(-0.25, 0.25), r * f, sides=5, turn=turn)
             for h, f in levels]
    loft(mesh, "building_roof", rings, col, cap_top=True, cap_bottom=True)


# ---- models placed by lap distance (local frame: -z = forward, +x = right) ----------------
def pit_building():
    """The temporary pit building on Azadliq Square: about 270 m long, garages under a glazed
    hospitality floor and an open roof terrace under canopies (photographs of the 2016 to 2024
    races). The map has it as a 275 x 26 m "carport"; the model keeps that length and 17 m of
    the depth, the rest is the pit lane in front of it. Local x = 0 is the front (the garage
    doors), the building extends to -x; z runs from -135 to +135."""
    m = sg.SceneryMesh(-1.0e6, -1.0e6, 2.0e6)
    m.anchor(0.0, 0.0)
    length, depth = 270.0, 17.0
    white = (0.86, 0.86, 0.84, 1.0)
    # Ground floor: a dark band of open garages between white piers.
    sg.box(m, "concrete", (-depth, -0.5, -0.5 * length), (0.0, 0.25, 0.5 * length), (0.30, 0.30, 0.31, 0.0))
    bays = 36
    bay = length / bays
    for k in range(bays + 1):
        zc = -0.5 * length + k * bay
        sg.box(m, "concrete", (-depth, 0.0, zc - 0.35), (0.25, 4.6, zc + 0.35), WHITE)
    sg.box(m, "concrete", (-depth, 0.0, -0.5 * length), (-1.2, 4.6, 0.5 * length), DARK)
    sg.box(m, "concrete", (-depth, 4.6, -0.5 * length), (0.9, 5.4, 0.5 * length), WHITE)       # fascia / balcony
    # Hospitality floor: glass front, white ends and back.
    ring = np.array([[-depth, -0.5 * length], [0.0, -0.5 * length], [0.0, 0.5 * length], [-depth, 0.5 * length]])
    sg.prism(m, ring, [], 5.4, 9.6, "building_glass", "building_roof", (0.30, 0.42, 0.52, 1.0),
             (0.80, 0.80, 0.78, 0.0), 5.4)
    sg.box(m, "concrete", (-depth - 0.2, 9.6, -0.5 * length - 0.2), (0.9, 10.0, 0.5 * length + 0.2), WHITE)
    # Roof terrace: a row of white canopies on posts.
    for k in range(18):
        zc = -0.5 * length + (k + 0.5) * length / 18.0
        sg.box(m, "building_roof", (-depth + 2.0, 12.6, zc - 6.4), (-1.0, 12.9, zc + 6.4), (0.90, 0.90, 0.88, 0.0))
        for px in (-depth + 2.4, -1.4):
            for pz in (zc - 6.0, zc + 6.0):
                sg.box(m, "metal", (px - 0.1, 10.0, pz - 0.1), (px + 0.1, 12.6, pz + 0.1), STEEL)
    # Race control tower at the Turn 1 end.
    ring = np.array([[-depth, -0.5 * length - 14.0], [0.0, -0.5 * length - 14.0], [0.0, -0.5 * length - 0.4],
                     [-depth, -0.5 * length - 0.4]])
    sg.prism(m, ring, [], -0.5, 15.5, "building_glass", "building_roof", (0.30, 0.42, 0.52, 1.0),
             (0.80, 0.80, 0.78, 0.0), 0.0)
    # Pit wall: timing stands along the track edge of the pit lane (x = 11.6 to 13.6: 3 m and more from the road, behind the wall).
    for k in range(10):
        zc = -100.0 + k * 22.0
        sg.box(m, "metal", (12.9, 0.0, zc - 5.0), (13.2, 2.9, zc - 4.7), STEEL)
        sg.box(m, "metal", (12.9, 0.0, zc + 4.7), (13.2, 2.9, zc + 5.0), STEEL)
        sg.box(m, "building_roof", (11.6, 2.9, zc - 5.2), (13.6, 3.1, zc + 5.2), (0.82, 0.82, 0.80, 0.0))
    return m


def start_gantry(span):
    """The start lights gantry: a steel truss on two legs with the five light pods and a board
    above them (Wikimedia Commons, "Start backshot Baku 2016.jpg")."""
    m = sg.SceneryMesh(-1.0e6, -1.0e6, 2.0e6)
    m.anchor(0.0, 0.0)
    half = 0.5 * span
    for sx in (-1.0, 1.0):
        sg.box(m, "metal", (sx * half - 0.35, -0.3, -0.35), (sx * half + 0.35, 8.2, 0.35), STEEL)
    sg.box(m, "metal", (-half, 7.0, -0.45), (half, 8.2, 0.45), STEEL)
    sg.box(m, "building_roof", (-half + 1.0, 8.2, -0.12), (half - 1.0, 10.0, 0.12), BOARDS[0])
    for k in range(5):
        xc = (k - 2) * 1.1
        sg.box(m, "concrete", (xc - 0.42, 5.9, 0.30), (xc + 0.42, 7.0, 0.62), DARK)
        sg.box(m, "emissive_light", (xc - 0.25, 6.1, 0.62), (xc + 0.25, 6.6, 0.66), (1.0, 1.0, 1.0, 0.0))
    return m


# ---- models in world coordinates relative to their own centre ------------------------------
def flame_towers(lap):
    """The three Flame Towers on the hill above Turn 15: each a flame, a rounded triangle in
    plan that swells to a third of its height and then leans and tapers to a point. Glass all
    over. Returns the mesh and the plan position of its origin."""
    rings = [lap.feature(ref).outers[0] for ref, _ in FLAME_TOWERS]
    origin = np.mean([r.mean(axis=0) for r in rings], axis=0)
    y0 = min(float(lap.ground.height(r[:, 0], r[:, 1]).min()) for r in rings)
    base = float(lap.ground.height(origin[0], origin[1]))
    m = sg.SceneryMesh(-1.0e6, -1.0e6, 2.0e6)
    m.anchor(0.0, 0.0)
    for (ref, height), ring in zip(FLAME_TOWERS, rings):
        c = ring.mean(axis=0) - origin
        radius = math.sqrt(abs(sg.signed_area(ring)) / math.pi)
        lean = -c / max(np.linalg.norm(c), 1e-6)      # the tips lean towards each other
        sections = []
        for t in np.linspace(0.0, 1.0, 12):
            scale = (1.0 + 0.22 * math.sin(math.pi * min(t / 0.6, 1.0))) * (1.0 - t ** 2.2) if t < 1.0 else 0.0
            shift = lean * radius * 0.9 * t ** 2
            y = (y0 - base - 2.0) + t * (height + 2.0)
            sections.append(circle(c[0] + shift[0], y, c[1] + shift[1], max(radius * scale, 0.05), sides=9,
                                   turn=math.atan2(lean[1], lean[0])))
        loft(m, "building_glass", sections, (0.34, 0.50, 0.66, 1.0), cap_top=False)
    return m, origin


def tv_tower():
    """Baku TV Tower: a tapering concrete shaft, the pod of the revolving restaurant at
    175 m and the steel antenna to 310 m."""
    m = sg.SceneryMesh(-1.0e6, -1.0e6, 2.0e6)
    m.anchor(0.0, 0.0)
    grey = (0.60, 0.60, 0.58, 0.0)
    profile = [(-5.0, 14.0), (0.0, 14.0), (30.0, 8.5), (100.0, 6.0), (168.0, 5.2)]
    loft(m, "concrete", [circle(0.0, y, 0.0, r, sides=10) for y, r in profile], grey, cap_top=False)
    pod = [(168.0, 5.2), (173.0, 13.0), (186.0, 14.0), (192.0, 8.0), (204.0, 5.0)]
    loft(m, "building_glass", [circle(0.0, y, 0.0, r, sides=12) for y, r in pod], (0.42, 0.50, 0.58, 1.0))
    mast = [(204.0, 3.2), (250.0, 2.0), (252.0, 1.1), (310.0, 0.4)]
    loft(m, "metal", [circle(0.0, y, 0.0, r, sides=6) for y, r in mast], (0.70, 0.25, 0.22, 0.0))
    return m


# ---- the world-space model ---------------------------------------------------------------
def stone_wall(mesh, lap, ref, height):
    """The fortress wall from its mapped outline: limestone, cut back behind the barrier, with
    merlons along the top. The round bastions are part of the outline."""
    f = lap.feature(ref)
    for ring in lap.corridor.cut(f.outers[0], 2.6):
        ring = sg.oriented(sg.clean_ring(ring), True)
        if len(ring) < 3:
            continue
        g = float(lap.ground.height(ring[:, 0], ring[:, 1]).min())
        mesh.anchor(*ring.mean(axis=0))
        sg.prism(mesh, ring, [], g - 1.5, g + height, "concrete", "concrete", SANDSTONE, SANDSTONE_DARK, g)
        # Merlons: a block every 2.4 m along the outline, set just inside it.
        for a, b in zip(ring, np.roll(ring, -1, axis=0)):
            length = float(np.hypot(*(b - a)))
            if length < 2.0:
                continue
            d = (b - a) / length
            inward = np.array([-d[1], d[0]])
            if not in_any(0.5 * (a + b) + inward * 0.4, [ring]):
                inward = -inward
            for k in range(int(length // 2.4)):
                p = a + d * (1.2 + 2.4 * k)
                oriented_box(mesh, "concrete", p + inward * 0.35, d, 0.6, 0.3, g + height, g + height + 0.9, SANDSTONE)


def maiden_tower(mesh, lap):
    """Qiz Qalasi: a limestone drum 29.5 m high and 16.5 m across with the long buttress on its
    seaward side; the mapped outline has both. Ribbed above the lower third, which the model
    shows as a darker upper band."""
    ring = sg.oriented(sg.clean_ring(lap.feature("way/299418016").outers[0]), True)
    g = float(lap.ground.height(ring[:, 0], ring[:, 1]).min())
    mesh.anchor(*ring.mean(axis=0))
    sg.prism(mesh, ring, [], g - 1.5, g + 10.0, "concrete", "concrete", SANDSTONE, SANDSTONE_DARK, g)
    sg.prism(mesh, ring, [], g + 10.0, g + 29.5, "concrete", "concrete", SANDSTONE_DARK, SANDSTONE_DARK, g)


def trackside(lap):
    rng = np.random.default_rng(20160619)     # the first race in Baku
    mesh = sg.SceneryMesh(0.0, 0.0, sg.CHUNK)
    c = lap.corridor
    stone_wall(mesh, lap, "way/1502989778", 9.5)
    stone_wall(mesh, lap, "way/1502989779", 9.5)
    maiden_tower(mesh, lap)

    # Where nothing may be planted: buildings, stands, the pit building and its lane.
    solid = [f.outers[0] for f in lap.buildings if float(c.nearest(f.outers[0])[2].min()) < 60.0]
    solid += [lap.band(s0 - 4.0, s1 + 4.0, side, d0 - 3.0, d0 + depth + 2.0) for _, s0, s1, side, d0, depth, _ in STANDS]
    solid.append(lap.band(5985.0, 310.0, -1, 0.0, 36.0))
    solid += [lap.band(s - 0.5 * width - 3.0, s + 0.5 * width + 3.0, side, d - 2.5, d + 4.0)
              for s, side, d, width in SCREENS]

    def blocked(p, clearance=2.2):
        if in_any(p, solid):
            return True
        return any(in_any(p + np.array(d) * clearance, solid) for d in ((1, 0), (-1, 0), (0, 1), (0, -1)))

    planted = []

    def plant(p, kind, height=None):
        idx, lat, dist = c.nearest(p[None])
        i = int(idx[0])
        if dist[0] < c.half[i] + 3.6 or blocked(p):
            return
        if any(np.hypot(*(p - q)) < 4.5 for q in planted[-60:]):
            return
        planted.append(p)
        # Beside the road the ground is the road's own verge; further out it is the terrain.
        near = dist[0] < c.half[i] + 18.0
        y = float(c.y[i]) - 0.1 if near else float(lap.ground.height(p[0], p[1]))
        if kind == "boulevard":
            kind = ["pine", "plane", "plane", "cypress", "palm"][int(rng.integers(5))]
        h = height or {"plane": rng.uniform(9.0, 13.0), "pine": rng.uniform(9.0, 14.0),
                       "cypress": rng.uniform(8.0, 12.0), "palm": rng.uniform(6.0, 9.0)}[kind]
        mesh.anchor(p[0], p[1])
        tree(mesh, p[0], y, p[1], float(h), kind, rng)

    # 1. The mapped trees and tree rows that stand on the 30 m verge, where the surroundings
    #    step plants nothing (it treats the verge as run-off).
    for f in lap.feats:
        pts = None
        if f.point is not None and f.tags.get("natural") == "tree":
            pts = f.point[None]
        elif f.line is not None and f.tags.get("natural") == "tree_row":
            pts, _ = su._resample(f.line, 8.0)
        if pts is None:
            continue
        for p in pts[c.keep_out(pts)]:
            plant(np.asarray(p, dtype=np.float64), "plane" if rng.uniform() < 0.75 else "pine")
    mapped = len(planted)
    # 2. The rows of the avenues.
    for s0, s1, side, d, spacing, kind in TREE_ROWS:
        for s in lap.stretch(s0, s1, spacing):
            p = lap.point(s + rng.uniform(-1.0, 1.0), side, d + rng.uniform(-0.4, 0.4))[[0, 2]]
            if c.keep_out(p[None])[0]:      # beyond the verge the baked trees take over
                plant(p, kind)

    # Advertising boards on the debris fence, 12 m panels.
    for s0, s1, side in BOARD_RUNS:
        for k, s in enumerate(lap.stretch(s0, s1, 12.4)[:-1]):
            i = lap.index(s + 6.0)
            p = lap.point(s + 6.0, side, 3.4)
            mesh.anchor(p[0], p[2])
            oriented_box(mesh, "building_roof", p[[0, 2]], c.tan[i], 5.9, 0.06, p[1] + 1.15, p[1] + 2.15,
                         BOARDS[(k + int(s0)) % len(BOARDS)])

    # Frames of the big screens (the screens themselves are in the recipe).
    for s, side, d, width in SCREENS:
        i = lap.index(s)
        for e in (-0.5, 0.5):
            p = lap.point(s + e * width, side, d + 0.9)
            mesh.anchor(p[0], p[2])
            oriented_box(mesh, "metal", p[[0, 2]], c.tan[i], 0.25, 0.25, p[1] - 0.3, p[1] + 11.0, STEEL)
    print(f"trackside: {mapped} mapped trees on the verge, {len(planted) - mapped} avenue trees")
    return mesh


# ---- output ------------------------------------------------------------------------------
def write_models(lap):
    out = OUT / "landmarks"
    out.mkdir(exist_ok=True)
    entries = []

    def save(name, mesh):
        stats = sg.write_glb(out / f"{name}.glb", mesh, f"{ID}_{name}", "fun-racer tools/track/landmarks/baku.py")
        print(f"  {name}.glb: {stats['triangles']} triangles, {stats['bytes'] / 1024:.0f} kB")

    # The pit building: front 14 m from the left road edge (the pit lane), from the finish
    # line to the braking zone of Turn 1; its middle is at s = 150.
    save("pit_building", pit_building())
    i = lap.index(150.0)
    entries.append({"model": "pit_building", "at": {"s": 150.0, "side": -1, "dist": round(float(lap.corridor.half[i]) + 16.6, 2)}})
    # Start lights over the grid's start line (start_s of track.json).
    start = float(lap.track["start_s"])
    save("start_gantry", start_gantry(2.0 * float(lap.corridor.half[lap.index(start)]) + 7.0))
    entries.append({"model": "start_gantry", "at": {"s": round(start - 6.0, 1), "side": 1, "dist": 0.0}})
    mesh, origin = flame_towers(lap)
    save("flame_towers", mesh)
    entries.append({"model": "flame_towers", "at": {"xz": [round(float(origin[0]), 2), round(float(origin[1]), 2)]}})
    save("tv_tower", tv_tower())
    x, z = lap.proj.to_xz(TV_TOWER[0], TV_TOWER[1])
    entry = {"model": "tv_tower", "at": {"latlon": [TV_TOWER[0], TV_TOWER[1]]}}
    if not lap.ground.in_near(x, z):    # beyond the near terrain a landmark is placed at y = 0
        entry["y_offset"] = round(float(lap.ground.height(x, z)), 1)
    entries.append(entry)
    # Everything in world coordinates hangs on the origin; landmarks sit on the terrain, so
    # its height there is taken out again.
    save("trackside", trackside(lap))
    entries.append({"model": "trackside", "at": {"xz": [0.0, 0.0]},
                    "y_offset": round(-float(lap.ground.height(0.0, 0.0)), 3)})
    (OUT / "landmarks.json").write_text(json.dumps(entries, indent=1) + "\n")
    print(f"landmarks.json: {len(entries)} entries")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--recipe", action="store_true", help="rewrite the generated block of the recipe")
    args = ap.parse_args()
    lap = Lap()
    if args.recipe:
        write_recipe(lap)
    else:
        write_models(lap)


if __name__ == "__main__":
    main()
