"""Marina Bay: the hand-made part of the surroundings.

    .venv/bin/python tools/track/landmarks/marina_bay.py models   # landmarks/*.glb, landmarks.json
    .venv/bin/python tools/track/landmarks/marina_bay.py recipe   # rewrites the generated block
                                                                  # of tracks/marina_bay.toml

Both read assets/tracks/marina_bay/track.json (and the cached map answers in raw/), so run them
after the centreline step and before the surroundings step:

    build_track.py marina_bay --offline --steps centreline,road,terrain
    landmarks/marina_bay.py recipe && landmarks/marina_bay.py models
    build_track.py marina_bay --offline --steps surroundings,info

`recipe` writes everything that is placed by its distance round the lap (grandstands, their
roofs, gantries, the footbridge, the paddock) and everything that is taken over from the map
in another form (the water of the bay as one level body, the lawns), as [[surroundings.*]]
entries between two marker lines of the recipe. `models` writes the structures that have a
shape of their own.

Sources of the dimensions are given at each model. Local frame of a model: x = right of the
race direction, y = up, -z = the race direction (for a model placed by lat / lon: -z is the
direction its yaw_deg turns to), origin on the ground.
"""
from __future__ import annotations

import glob
import json
import math
import os
import re
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "cad" / "track"))
import scenery_glb as sg  # noqa: E402

TRACK_ID = "marina_bay"
FOLDER = ROOT / "assets" / "tracks" / TRACK_ID
RECIPE = ROOT / "tools" / "track" / "tracks" / f"{TRACK_ID}.toml"
BEGIN = "# >>> generated by tools/track/landmarks/marina_bay.py recipe (do not edit by hand)"
END = "# <<< generated"
EARTH = 111319.49079327357
GENERATOR = "fun-racer tools/track/landmarks/marina_bay.py"

# Colours, sRGB as seen in the reference photographs (converted to linear on writing).
JADE = (0.50, 0.74, 0.64)          # roofs and bands of the pit building
PIT_GREY = (0.47, 0.48, 0.50)
PIT_LIGHT = (0.74, 0.75, 0.76)
GLASS = (0.30, 0.42, 0.46)
STEEL_WHITE = (0.82, 0.84, 0.84)   # Anderson Bridge, the Flyer
STONE = (0.72, 0.70, 0.64)
DURIAN = (0.50, 0.58, 0.55)        # aluminium sunshades of the Esplanade


def lin(rgb, a=0.0):
    return tuple(((c / 12.92) if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4) for c in rgb) + (a,)


# ----------------------------------------------------------------------------- the lap
class Lap:
    """track.json in plan view: lat / lon <-> metres <-> (s, lateral); lateral > 0 = right."""

    def __init__(self, folder=FOLDER):
        with open(folder / "track.json", encoding="utf-8") as f:
            t = json.load(f)
        with open(folder / "terrain.json", encoding="utf-8") as f:
            terrain = json.load(f)
        self.k = terrain["plan_scale"]
        near = terrain["near"]
        self.near_rect = (near["x0"], near["x0"] + (near["nx"] - 1) * near["step"],
                          near["z0"], near["z0"] + (near["nz"] - 1) * near["step"])
        self.lat0, self.lon0 = t["origin_latlon"]
        self.kx = EARTH * math.cos(math.radians(self.lat0))
        self.length = float(t["length"])
        self.start_s = float(t["start_s"])
        pts = np.array([p["p"] for p in t["points"]], dtype=float)
        self.xz, self.y = pts[:, [0, 2]], pts[:, 1]
        self.s = np.array([p["s"] for p in t["points"]], dtype=float)
        self.width = np.array([p["width"] for p in t["points"]], dtype=float)
        d = np.roll(self.xz, -1, axis=0) - np.roll(self.xz, 1, axis=0)
        self.tan = d / np.linalg.norm(d, axis=1)[:, None]
        self.right = np.stack([-self.tan[:, 1], self.tan[:, 0]], axis=1)
        self.turns = {u["id"]: float(u["s_apex"]) for u in t["turns"]}

    def to_xz(self, lat, lon):
        return (np.asarray(lon) - self.lon0) * self.kx * self.k, -(np.asarray(lat) - self.lat0) * EARTH * self.k

    def to_ll(self, x, z):
        return self.lat0 - (z / self.k) / EARTH, self.lon0 + (x / self.k) / self.kx

    def index(self, s):
        return int(round((s % self.length) / self.length * len(self.s))) % len(self.s)

    def at(self, s, lateral=0.0):
        i = self.index(s)
        return self.xz[i] + self.right[i] * lateral

    def half(self, s):
        return 0.5 * float(self.width[self.index(s)])

    def height(self, s):
        return float(self.y[self.index(s)])

    def locate(self, x, z):
        i = int(np.argmin(np.hypot(self.xz[:, 0] - x, self.xz[:, 1] - z)))
        v = np.array([x, z]) - self.xz[i]
        return float(self.s[i] + v @ self.tan[i]), float(v @ self.right[i])

    def distance(self, pts):
        pts = np.asarray(pts, dtype=float).reshape(-1, 2)
        out = np.empty(len(pts))
        for k, p in enumerate(pts):
            out[k] = np.hypot(self.xz[:, 0] - p[0], self.xz[:, 1] - p[1]).min()
        return out

    def strip(self, s0, s1, lat0, lat1, step=12.0):
        """Ring in metres along the lap from s0 to s1 between two lateral offsets, each measured
        from the road EDGE on its side (negative = left of the left edge)."""
        span = (s1 - s0) % self.length
        n = max(2, int(span / step) + 1)
        ss = [s0 + span * k / (n - 1) for k in range(n)]

        def off(s, lat):
            return self.at(s, lat + math.copysign(self.half(s), lat))

        return np.array([off(s, lat0) for s in ss] + [off(s, lat1) for s in reversed(ss)])

    def across(self, s, lat0, lat1, depth):
        """Ring of a beam across the road at s, lateral offsets from the centreline."""
        i = self.index(s)
        c, r, t = self.xz[i], self.right[i], self.tan[i] * (0.5 * depth)
        return np.array([c + r * lat0 - t, c + r * lat1 - t, c + r * lat1 + t, c + r * lat0 + t])


# ----------------------------------------------------------------------------- the map cache
def cache_elements(kind):
    files = sorted(glob.glob(str(FOLDER / "raw" / f"surroundings_{kind}_*.json")))
    if not files:
        raise SystemExit(f"no surroundings_{kind}_*.json in {FOLDER / 'raw'}")
    with open(files[0], encoding="utf-8") as f:
        return json.load(f)["elements"]


def element_ring(e):
    """Outline in (lat, lon): the way, or the longest outer ring of a relation."""
    flat = e.get("g") or max(e.get("o") or [[]], key=len)
    return np.array(flat, dtype=float).reshape(-1, 2)


def simplify(ring, tol):
    """Douglas-Peucker on a closed ring in metres."""
    ring = np.asarray(ring, dtype=float)
    if len(ring) < 5:
        return ring
    far = int(np.argmax(np.hypot(*(ring - ring[0]).T)))

    def dp(pts):
        if len(pts) < 3:
            return pts
        a, b = pts[0], pts[-1]
        ab = b - a
        n = max(float(np.hypot(*ab)), 1e-9)
        d = np.abs(ab[0] * (pts[:, 1] - a[1]) - ab[1] * (pts[:, 0] - a[0])) / n
        k = int(np.argmax(d))
        if d[k] <= tol:
            return np.array([a, b])
        return np.concatenate([dp(pts[:k + 1])[:-1], dp(pts[k:])])

    one = dp(ring[:far + 1])
    two = dp(np.concatenate([ring[far:], ring[:1]]))
    return np.concatenate([one[:-1], two[:-1]])


# ----------------------------------------------------------------------------- recipe block
def fmt_ring(lap, ring):
    lat, lon = lap.to_ll(ring[:, 0], ring[:, 1])
    return "[" + ", ".join(f"[{a:.6f}, {b:.6f}]" for a, b in zip(lat, lon)) + "]"


def add(lap, out, ring, kind, note, height=None, min_height=None):
    out.append(f"[[surroundings.add]]    # {note}")
    out.append(f"polygon = {fmt_ring(lap, np.asarray(ring, dtype=float))}")
    out.append(f'kind = "{kind}"')
    if height is not None:
        out.append(f"height = {height:.1f}")
    if min_height is not None:
        out.append(f"min_height = {min_height:.1f}")
    out.append("")


# Water of the map that is replaced: the polygons of the bay and the river reach under the
# bridges and along the walls of the lap, where the baked ground is the road, and the step
# then cuts them into 150 m squares at different levels (one of them at deck height).
WATER_POLYGONS = {9569901: "Singapore River", 9542146: "Marina Reservoir (the bay and the Kallang Basin)"}
WATER_LINES = [692147571, 692147572, 692181240, 692181242, 692181245, 692181247, 694064998, 694091088]
CORRIDOR = 125.0       # m from the centreline: the baked ground is the road's there
BORDER = 175.0         # m inside the near terrain rectangle: the ground blends to the far grid
LAWN_REACH = 230.0     # lawns of the map are taken over within this distance of the lap
LAWN_MIN_AREA = 500.0
# Paved or built over on race weekend, although the map shows a park.
NOT_LAWN = {687917300,      # Merlion Park: a granite terrace
            395120471}      # Youth Olympic Park: under the works of NS Square
GREEN = {"leisure": {"park", "garden", "pitch", "common"},
         "landuse": {"grass", "meadow", "village_green", "recreation_ground"}}


def ground_height(pts):
    """Baked terrain height (m above the finish line) at plan points, bilinear."""
    with open(FOLDER / "terrain.json", encoding="utf-8") as f:
        near = json.load(f)["near"]
    grid = np.fromfile(FOLDER / near["file"], dtype="<f4").reshape(near["nz"], near["nx"])
    pts = np.asarray(pts, dtype=float).reshape(-1, 2)
    u = np.clip((pts[:, 0] - near["x0"]) / near["step"], 0.0, near["nx"] - 1.001)
    v = np.clip((pts[:, 1] - near["z0"]) / near["step"], 0.0, near["nz"] - 1.001)
    i, j = u.astype(int), v.astype(int)
    tu, tv = u - i, v - j
    top = grid[j, i] + (grid[j, i + 1] - grid[j, i]) * tu
    bot = grid[j + 1, i] + (grid[j + 1, i + 1] - grid[j + 1, i]) * tu
    return top + (bot - top) * tv


def water_blocks(lap, out):
    """The step gives a water polygon one level, the 15th percentile of the ground under its
    outline, when the 10th and 90th percentile are within 2 m; otherwise it cuts the polygon
    into 150 m squares, each at its own level. The ground is not the water's level beside the
    lap (there it is the road) nor in the border band of the near terrain rectangle (there it
    blends into the coarse far grid). So the outlines get extra points on open ground until
    93 % of their points are there. What is left of the surface model still falls by a metre
    from the river to the Kallang Basin, so the river comes out about a metre above the bay:
    the step between them is under the east side of the Esplanade Bridge."""
    out.append("# Water: the map's polygons, simplified, cut at the near terrain rectangle, with extra points")
    out.append("# on their far shores that steer the level the step gives them (see the generator).")
    for ref in list(WATER_POLYGONS) + WATER_LINES:
        kind = "relation" if ref in WATER_POLYGONS else "way"
        out.append(f'[[surroundings.exclude]]\nosm = "{kind}/{ref}"')
    out.append("")
    far = {e["id"]: e for e in cache_elements("far") if e["t"] == "r"}
    x0, x1, z0, z1 = lap.near_rect

    def off_level(pts):
        pts = np.asarray(pts, dtype=float).reshape(-1, 2)
        edge = np.minimum(np.minimum(pts[:, 0] - x0, x1 - pts[:, 0]), np.minimum(pts[:, 1] - z0, z1 - pts[:, 1]))
        return (lap.distance(pts) < CORRIDOR) | (edge < BORDER)

    def densify(ring, usable, done):
        """Adds points on the longest edges whose ends and middle are `usable`, until
        done(off-level flags, ground heights) of the ring's points; None when it runs out of
        edges."""
        ring = [np.asarray(p, dtype=float) for p in ring]
        off = list(off_level(ring))
        g = list(ground_height(ring))
        ok = list(usable(np.array(ring)))
        for _ in range(4000):
            if done(np.array(off), np.array(g)):
                return np.array(ring)
            best, k = 0.5, -1
            for i in range(len(ring)):
                j = (i + 1) % len(ring)
                if ok[i] and ok[j]:
                    d = float(np.hypot(*(ring[j] - ring[i])))
                    if d > best:
                        best, k = d, i
            if k < 0:
                return None
            a, b = ring[k], ring[(k + 1) % len(ring)]
            # A hair off the edge, so that the point is not dropped as collinear.
            q = 0.5 * (a + b) + (b - a)[::-1] * np.array([1.0, -1.0]) / best * 0.05
            ring.insert(k + 1, q)
            off.insert(k + 1, bool(off_level(q)[0]))
            g.insert(k + 1, float(ground_height(q)[0]))
            ok.insert(k + 1, bool(usable(q[None])[0]))
        return None

    for ref, name in WATER_POLYGONS.items():
        ll = element_ring(far[ref])
        x, z = lap.to_xz(ll[:, 0], ll[:, 1])
        whole = simplify(np.stack([x, z], axis=1), 10.0)
        ring = whole
        for a, b, c in ((1.0, 0.0, -x0), (-1.0, 0.0, x1), (0.0, 1.0, -z0), (0.0, -1.0, z1)):
            ring = sg.clip_halfplane(ring, a, b, c)
        ring = densify(ring, lambda p: ~off_level(p), lambda off, g: off.mean() <= 0.07)
        if ring is None:
            raise SystemExit(f"{name}: not enough shore on open ground to level the water on")
        level = float(np.percentile(ground_height(ring), 15))
        add(lap, out, ring, "water", f"{name}: {len(ring)} points, comes out at {level:+.2f} m")
        for label, (a, b, c) in (("west", (-1.0, 0.0, x0 - 1.0)), ("east", (1.0, 0.0, -x1 - 1.0)),
                                 ("north", (0.0, -1.0, z0 - 1.0)), ("south", (0.0, 1.0, -z1 - 1.0))):
            piece = sg.clip_halfplane(whole, a, b, c)
            if len(piece) >= 3 and abs(sg.signed_area(piece)) > 400.0:
                add(lap, out, piece, "water", f"{name}, {label} of the detailed ground")


def lawn_blocks(lap, out):
    out.append("# Lawns. The land-cover class \"grass\" is what the map says nothing about, which here is")
    out.append("# paving (environment.json paints it grey); the real lawns of the map near the lap are")
    out.append("# repeated as \"farmland\", which environment.json paints as mown grass.")
    rows = []
    for e in cache_elements("near"):
        t = e.get("tags", {})
        if e["t"] == "n" or e["id"] in NOT_LAWN or "building" in t:
            continue
        if not any(t.get(k) in v for k, v in GREEN.items()):
            continue
        ll = element_ring(e)
        if len(ll) < 4:
            continue
        x, z = lap.to_xz(ll[:, 0], ll[:, 1])
        ring = np.stack([x, z], axis=1)
        if lap.distance(ring).min() > LAWN_REACH or abs(sg.signed_area(ring)) < LAWN_MIN_AREA:
            continue
        ring = simplify(ring, 1.5)
        name = t.get("name") or t.get("leisure") or t.get("landuse")
        ref = f"{'relation' if e['t'] == 'r' else 'way'} {e['id']}"
        rows.append((lap.locate(*ring.mean(axis=0))[0], ref, name, ring))
    for s, ref, name, ring in sorted(rows, key=lambda r: (-abs(sg.signed_area(r[3])))):
        add(lap, out, ring, "farmland", f"{name} ({ref}), near s = {s:.0f}")


# Grandstands of the race weekend: none of them is on the map. Positions from the organiser's
# circuit park map (singaporegp.sg) and the photographs listed in the pull request; sizes are
# estimates from those photographs (row count and bays). [name, s from, s to, side (+1 right),
# gap to the road edge, depth, height of the top row, roof]
STANDS = [
    ("Pit Grandstand", 45.0, 330.0, 1, 9.0, 24.0, 13.0, True),
    ("Turn 1 Grandstand", 338.0, 385.0, 1, 12.0, 20.0, 11.0, False),
    ("Turn 2 Grandstand", 500.0, 560.0, -1, 10.0, 16.0, 9.0, False),
    ("Republic Grandstand", 640.0, 715.0, 1, 9.0, 14.0, 8.0, False),
    ("Stamford Grandstand", 1870.0, 1985.0, 1, 9.0, 18.0, 10.0, False),
    ("Padang Grandstand", 2330.0, 2590.0, -1, 10.0, 26.0, 13.0, False),
    ("Empress Grandstand", 2745.0, 2795.0, 1, 9.0, 12.0, 7.0, False),
    ("Connaught Grandstand", 3440.0, 3560.0, -1, 10.0, 18.0, 10.0, False),
    ("Esplanade Waterfront Grandstand", 3935.0, 4015.0, 1, 9.0, 16.0, 9.0, False),
    ("Turn 16 stand", 4255.0, 4330.0, -1, 9.0, 12.0, 7.0, False),
    ("Turn 17 stand", 4450.0, 4530.0, 1, 9.0, 14.0, 8.0, False),
    ("Turn 18 stand", 4600.0, 4680.0, -1, 10.0, 12.0, 7.0, False),
    ("Turn 19 hospitality stand", 4850.0, 4910.0, 1, 14.0, 20.0, 12.0, True),
]
# Banner bridges over the road (the red sponsor boards of the reference photographs).
BANNERS = [20.0, 250.0, 1300.0, 2440.0, 3720.0, 4120.0]


def trackside_blocks(lap, out):
    out.append("# Race-weekend structures, placed by their distance round the lap.")
    for name, s0, s1, side, gap, depth, top, roof in STANDS:
        a, b = side * gap, side * (gap + depth)
        add(lap, out, lap.strip(s0, s1, a, b), "grandstand", f"{name}, s = {s0:.0f} to {s1:.0f}", height=top)
        if roof:
            add(lap, out, lap.strip(s0, s1, side * (gap + 3.0), side * (gap + depth + 1.5)), "metal",
                f"roof of the {name}", height=top + 5.4, min_height=top + 5.0)
    # Paddock behind the pit building, and the hard standing of the stands, on the lawn the
    # map draws round the pit complex.
    add(lap, out, lap.strip(4880.0, 330.0, -1.0, -95.0, 20.0), "paved", "pit lane and paddock")
    add(lap, out, lap.strip(4880.0, 400.0, 1.0, 45.0, 20.0), "paved", "apron of the Pit Grandstand")
    # Start lights: a gantry 12 m beyond the start line; the lights hang over the road.
    s = lap.start_s + 12.0
    h = lap.half(s) + 3.2
    add(lap, out, lap.across(s, -h, h, 1.2), "metal", "start gantry", height=8.2, min_height=7.0)
    add(lap, out, lap.across(s - 0.7, -4.0, 4.0, 0.3), "light", "start lights", height=6.9, min_height=6.2)
    for sign in (-1.0, 1.0):
        add(lap, out, lap.across(s, sign * h - 0.4, sign * h + 0.4, 0.8), "metal", "start gantry post", height=8.2)
    for s in BANNERS:
        h = lap.half(s) + 3.2
        add(lap, out, lap.across(s, -h, h, 0.6), "metal", f"banner bridge at s = {s:.0f}", height=8.4, min_height=6.6)
        for sign in (-1.0, 1.0):
            add(lap, out, lap.across(s, sign * h - 0.3, sign * h + 0.3, 0.6), "metal", "banner bridge post", height=8.4)
    # The temporary footbridge over the road after Turn 16 (photograph of July 2026).
    s = lap.turns["T16"] + 38.0
    h = lap.half(s) + 5.0
    add(lap, out, lap.across(s, -h, h, 3.2), "metal", "footbridge after Turn 16", height=9.4, min_height=6.2)
    for sign in (-1.0, 1.0):
        add(lap, out, lap.across(s, sign * h - 2.5, sign * h + 2.5, 5.0), "concrete", "footbridge stair tower", height=9.4)
    # The link bridge between Millenia Walk and Marina Square over Raffles Boulevard. The map
    # has it (way 393090492) as a part 4.5 m above a ground that the step takes from beside
    # the road, 3 m lower: it came out as a slab across the road at windscreen height.
    s = 1392.0
    h = lap.half(s) + 14.0
    add(lap, out, lap.across(s, -h, h, 9.0), "building", "link bridge Millenia Walk - Marina Square", height=10.5, min_height=6.3)
    # NS Square: the floating platform and its grandstand were pulled down in 2023; the site is
    # a building yard with tower cranes. Two of them, 60 m under the hook (estimate).
    for k, (s, dist) in enumerate(((4010.0, 95.0), (4190.0, 120.0))):
        i = lap.index(s)
        c = lap.at(s, dist)
        r, t = lap.right[i], lap.tan[i]
        mast = np.array([c - r - t, c + r - t, c + r + t, c - r + t])
        add(lap, out, mast, "metal", f"tower crane {k + 1} at NS Square", height=62.0)
        jib = np.array([c - t * 14.0 - r * 0.8, c - t * 14.0 + r * 0.8, c + t * 46.0 + r * 0.8, c + t * 46.0 - r * 0.8])
        add(lap, out, jib, "metal", "its jib", height=63.6, min_height=62.0)


# Road bridges of the map. The step builds every bridge=* way as a deck on a straight grade and
# lifts it to 6.5 m where it crosses the lap. That is wrong twice here: the lap's own roads on
# the Anderson and Esplanade Bridges are such ways (a deck 6.5 m over the road), and the
# Benjamin Sheares Bridge (the East Coast Parkway viaduct, which the lap passes under four
# times) is far higher. Every bridge way that comes within BRIDGE_REACH of the centreline is
# left out; the viaduct and its slip roads are rebuilt as decks on piers at their real height.
BRIDGE_REACH = 45.0
# Deck height above the level of the finish line, by road class. The Benjamin Sheares Bridge
# is 29 m above the water at its main span (Wikipedia, "Benjamin Sheares Bridge"); where the
# lap passes under its approach spans the deck is about 15 m up (Commons: "Marina Bay Street
# Circuit near Singapore Flyer 11Jul2026 02", "Preparations for the 2023 Singapore Grand Prix -
# BugWarp 01"): estimate from the fence posts (2.5 m) in those photographs.
VIADUCT = {"motorway": 16.5, "motorway_link": 14.0, "trunk_link": 14.0}
DECK_DEPTH = 1.8
PIER_SPACING = 55.0


def bridge_blocks(lap, out):
    out.append("# Bridges of the map that cross or follow the lap (see the generator): left out, and the")
    out.append("# Benjamin Sheares Bridge rebuilt at its height, on piers.")
    drop, decks = [], []
    for e in cache_elements("near"):
        t = e.get("tags", {})
        if e["t"] != "w" or t.get("bridge") in (None, "no") or "highway" not in t or "g" not in e:
            continue
        ll = element_ring(e)
        x, z = lap.to_xz(ll[:, 0], ll[:, 1])
        line = np.stack([x, z], axis=1)
        # Resampled, so that a long straight way is tested along its whole length.
        seg = np.hypot(*np.diff(line, axis=0).T)
        d = np.concatenate([[0.0], np.cumsum(seg)])
        if d[-1] < 1.0:
            continue
        u = np.linspace(0.0, d[-1], max(2, int(d[-1] / 6.0) + 1))
        fine = np.stack([np.interp(u, d, line[:, 0]), np.interp(u, d, line[:, 1])], axis=1)
        if lap.distance(fine).min() > BRIDGE_REACH:
            continue
        drop.append(e["id"])
        # Only the parkway and its ramps: Esplanade Drive's bridges are the level road beside the lap.
        if t["highway"] in VIADUCT and t.get("layer") != "-1" and (t["highway"].startswith("motorway") or "East Coast" in t.get("name", "")):
            lanes = float(t.get("lanes", "2"))
            decks.append((e["id"], t.get("name", t["highway"]), VIADUCT[t["highway"]], lanes * 3.7 + 3.0, fine))
    for ref in sorted(drop):
        out.append(f'[[surroundings.exclude]]\nosm = "way/{ref}"')
    out.append("")
    for ref, name, top, width, fine in decks:
        tan = np.gradient(fine, axis=0)
        tan /= np.maximum(np.hypot(*tan.T), 1e-9)[:, None]
        right = np.stack([-tan[:, 1], tan[:, 0]], axis=1)
        cut = list(range(0, len(fine) - 1, 14)) + [len(fine) - 1]
        for a, b in zip(cut[:-1], cut[1:]):
            sl = slice(a, b + 1)
            ring = np.concatenate([fine[sl] - right[sl] * (0.5 * width), (fine[sl] + right[sl] * (0.5 * width))[::-1]])
            low = float(ground_height(ring).min())      # the step measures heights from here
            add(lap, out, ring, "concrete", f"{name} (way {ref}), deck {top:.1f} m above the finish line",
                height=top - low, min_height=top - DECK_DEPTH - low)
        for k in range(int(PIER_SPACING / 12.0), len(fine) - 2, int(PIER_SPACING / 6.0)):
            c, r, t = fine[k], right[k] * (0.3 * width), tan[k] * 1.3
            ring = np.array([c - r - t, c + r - t, c + r + t, c - r + t])
            if lap.distance(ring).min() < 12.0:
                continue        # no pier on the road or in its walls
            low = float(ground_height(ring).min())
            add(lap, out, ring, "concrete", "pier", height=top - DECK_DEPTH - low + 0.1)


def flyer_parts():
    """The Singapore Flyer of the map: one building:part column per capsule. Returns their ids,
    the hub in lat / lon and the unit direction of the wheel plane in (east, south)."""
    ids, pts = [], []
    for e in cache_elements("far"):
        t = e.get("tags", {})
        if e["t"] != "w" or "building" not in t and "building:part" not in t:
            continue
        ll = element_ring(e)
        try:
            h = float(t.get("height", "0"))
        except ValueError:
            continue
        c = ll.mean(axis=0)
        if 100.0 <= h <= 170.0 and abs(c[0] - 1.28930) < 0.0012 and abs(c[1] - 103.86310) < 0.0012 and len(ll) <= 8:
            ids.append(e["id"])
            pts.append(c)
    return ids, np.array(pts)


def recipe_block(lap):
    out = [BEGIN, ""]
    water_blocks(lap, out)
    lawn_blocks(lap, out)
    trackside_blocks(lap, out)
    bridge_blocks(lap, out)
    ids, _ = flyer_parts()
    out.append("# Replaced by models (landmarks.json): the pit building, the capsules of the Singapore")
    out.append("# Flyer (the map has one 150 m column per capsule) and the two shells of the Esplanade.")
    for ref in [49890775, 256163011, 256163012, 393090492] + sorted(ids):
        out.append(f'[[surroundings.exclude]]\nosm = "way/{ref}"')
    out += ["", END]
    return "\n".join(out) + "\n"


def write_recipe(lap):
    text = RECIPE.read_text(encoding="utf-8")
    block = recipe_block(lap)
    if BEGIN in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n", lambda m: block, text, flags=re.S)
    else:
        text = text.rstrip("\n") + "\n\n" + block
    RECIPE.write_text(text, encoding="utf-8")
    print(f"{RECIPE}: generated block of {block.count(chr(10))} lines")


# ----------------------------------------------------------------------------- mesh helpers
def new_mesh():
    return sg.SceneryMesh(-1.0e6, -1.0e6, 4.0e6)       # one chunk: one node per model


def beam(mesh, material, a, b, w, colour):
    """Square bar of side w from point a to point b."""
    a, b = np.asarray(a, dtype=float), np.asarray(b, dtype=float)
    d = b - a
    n = float(np.linalg.norm(d))
    if n < 1e-6:
        return
    d /= n
    ref = np.array([0.0, 1.0, 0.0]) if abs(d[1]) < 0.9 else np.array([1.0, 0.0, 0.0])
    u = np.cross(d, ref)
    u /= np.linalg.norm(u)
    v = np.cross(d, u)
    h = 0.5 * w
    mid = 0.5 * (a + b)
    for p, q in ((u, v), (v, -u), (-u, -v), (-v, u)):
        mesh.face(material, [a + p * h + q * h, a + p * h - q * h, b + p * h - q * h, b + p * h + q * h], None, colour,
                  away_from=mid)


def barrel(mesh, material, x0, x1, z0, z1, y_eave, rise, colour, n=6):
    """Barrel vault over the rectangle, its axis along z, plus the two gable ends."""
    xs = np.linspace(x0, x1, n + 1)
    t = (xs - x0) / (x1 - x0)
    ys = y_eave + rise * np.sin(np.pi * t)
    c = np.array([0.5 * (x0 + x1), y_eave - 5.0, 0.5 * (z0 + z1)])
    for k in range(n):
        mesh.face(material, [[xs[k], ys[k], z0], [xs[k + 1], ys[k + 1], z0], [xs[k + 1], ys[k + 1], z1], [xs[k], ys[k], z1]],
                  None, colour, away_from=c)
    for z in (z0, z1):
        mesh.face(material, [[x, y, z] for x, y in zip(xs, ys)], None, colour, away_from=c)


def write(mesh, name):
    stats = sg.write_glb(FOLDER / "landmarks" / f"{name}.glb", mesh, f"{TRACK_ID}_{name}", GENERATOR)
    print(f"  {name}.glb: {stats['triangles']} triangles, {stats['bytes'] / 1000:.0f} kB")
    return stats


# ----------------------------------------------------------------------------- models
def pit_building():
    """F1 Pit Building, 1 Republic Boulevard: 350 m long, three storeys (grandprix.com, 1 Sept
    2007; rental kit of the building, 2025), garages on the ground floor, glass fronts above
    with jade-green bands and barrel roofs, the race-control tower on stilts at the Turn 19 end
    (Commons: "Singapore (SG), Marina Bay Street Circuit, F1 Pit Building -- 2019 -- 4478",
    "Preparations for the 2023 Singapore Grand Prix - BugWarp 12 / 13"). Depth 34 m and the
    storey heights are read off those photographs. The track is on its +x side."""
    m = new_mesh()
    m.anchor(0.0, 0.0)
    grey, light, jade, glass = lin(PIT_GREY), lin(PIT_LIGHT), lin(JADE), lin(GLASS, 1.0)
    half, x0, x1 = 175.0, -17.0, 17.0
    sg.box(m, "building_wall", (x0, -1.5, -half), (x1, 5.2, half), grey)
    # Garage fronts: 36 doors seen as one dark, lit band.
    m.face("building_glass", [[x1 + 0.05, 0.3, -half + 6], [x1 + 0.05, 0.3, half - 6], [x1 + 0.05, 4.4, half - 6],
                              [x1 + 0.05, 4.4, -half + 6]], [1.0, 0.0, 0.0], glass)
    bays = 7
    span = 2.0 * half / bays
    for k in range(bays):
        z0, z1 = -half + k * span + 2.0, -half + (k + 1) * span - 2.0
        sg.box(m, "building_wall", (x0, 5.2, z0), (x1 + 1.5, 13.0, z1), light)
        for x, nx in ((x1 + 1.55, 1.0), (x0 - 0.05, -1.0)):
            m.face("building_glass", [[x, 5.6, z0 + 1], [x, 5.6, z1 - 1], [x, 12.2, z1 - 1], [x, 12.2, z0 + 1]],
                   [nx, 0.0, 0.0], glass)
        for y in (8.6, 12.3):   # the jade bands across the glass
            sg.box(m, "building_roof", (x1 + 1.5, y, z0), (x1 + 2.0, y + 0.7, z1), jade)
        barrel(m, "building_roof", x0 - 0.5, x1 + 2.0, z0, z1, 13.0, 3.6, jade)
    # The lettered fascia over the middle bays.
    sg.box(m, "building_wall", (x1 + 2.0, 9.6, -80.0), (x1 + 2.3, 11.4, 80.0), light)
    # Race control: a glass box on stilts beyond the south end, under its own scoop of a roof.
    z0, z1 = half + 6.0, half + 40.0
    for x in (x0 + 2.0, x1 + 4.0):
        for z in (z0 + 2.0, 0.5 * (z0 + z1), z1 - 2.0):
            beam(m, "metal", [x, -1.0, z], [x, 9.0, z], 0.7, light)
    sg.box(m, "building_glass", (x0, 9.0, z0), (x1 + 6.0, 14.5, z1), glass)
    sg.box(m, "metal", (x0 - 1.0, 8.5, z0 - 1.0), (x1 + 8.0, 9.0, z1 + 1.0), light)
    barrel(m, "building_roof", x0 - 2.0, x1 + 8.0, z0 - 1.0, z1 + 1.0, 14.5, 4.2, jade)
    sg.box(m, "building_wall", (x0, -1.5, half), (x0 + 8.0, 9.0, half + 6.0), grey)     # lift and stair core
    return m


def flyer():
    """Singapore Flyer: 165 m high, wheel 150 m across, 28 capsules of 7 x 4 m (Wikipedia,
    "Singapore Flyer"). A ladder-truss rim on cable spokes, carried by two legs on each side
    of the hub. The wheel is in the local x-y plane."""
    m = new_mesh()
    m.anchor(0.0, 0.0)
    white, lit = lin(STEEL_WHITE), lin((0.85, 0.92, 1.0))
    hub = np.array([0.0, 90.0, 0.0])
    r, n = 75.0, 28
    ang = np.arange(n) * (2.0 * np.pi / n)
    for side in (-1.3, 1.3):
        ring = [hub + np.array([r * math.cos(a), r * math.sin(a), side]) for a in ang]
        for k in range(n):
            beam(m, "metal", ring[k], ring[(k + 1) % n], 0.9, white)
    for k, a in enumerate(ang):
        d = np.array([math.cos(a), math.sin(a), 0.0])
        beam(m, "metal", hub + d * 3.0, hub + d * (r - 0.4), 0.22, white)                  # spoke
        c = hub + d * (r + 3.4)
        sg.box(m, "emissive_window", (c[0] - 3.5, c[1] - 1.6, -2.0), (c[0] + 3.5, c[1] + 1.6, 2.0), lit)
    beam(m, "metal", hub + [0.0, 0.0, -9.0], hub + [0.0, 0.0, 9.0], 5.0, white)            # spindle
    for z in (-9.0, 9.0):
        for x in (-22.0, 22.0):
            beam(m, "metal", hub + [0.0, 0.0, z], [x, 8.0, z * 2.6], 2.6, white)
    return m


def anderson_bridge(lap, s_mid, span):
    """Anderson Bridge (1910): 70 m long, 28 m wide, three steel bowstring trusses with ribs
    across them and a rusticated stone arch at each end (Wikipedia, "Anderson Bridge"). The
    lap uses the bay between the left and the middle truss; the other bay is paved for
    pedestrians (Commons: "Preparations for the 2023 Singapore Grand Prix - BugWarp 21 / 22 /
    23"). Truss height 7 m above the deck: read off those photographs. The trusses follow the
    hump of the road."""
    m = new_mesh()
    m.anchor(0.0, 0.0)
    steel, stone = lin(STEEL_WHITE), lin(STONE)
    half = 0.5 * span
    lines = (-6.9, 6.9, 20.7)       # the wall and fence of the lap stand inside the first two
    panels = 12
    zs = np.linspace(-half, half, panels + 1)
    y0 = lap.height(s_mid)

    def deck(z):
        return lap.height(s_mid - z) - y0

    def top(z):
        return deck(z) + 1.3 + 6.9 * (1.0 - (z / half) ** 2)

    for x in lines:
        for k in range(panels):
            a, b = zs[k], zs[k + 1]
            beam(m, "metal", [x, top(a), a], [x, top(b), b], 0.55, steel)                 # arch
            # Plate girder at parapet height.
            m_lo = min(deck(a), deck(b)) - 1.2
            for nx in (-1.0, 1.0):
                m.face("metal", [[x + nx * 0.25, m_lo, a], [x + nx * 0.25, m_lo, b], [x + nx * 0.25, deck(b) + 1.3, b],
                                 [x + nx * 0.25, deck(a) + 1.3, a]], [nx, 0.0, 0.0], steel)
            if 0 < k:
                beam(m, "metal", [x, deck(a) + 1.3, a], [x, top(a), a], 0.3, steel)        # hanger
            if 0 < k < panels - 1:
                lo, hi = (a, b) if k % 2 else (b, a)
                beam(m, "metal", [x, deck(lo) + 1.3, lo], [x, top(hi), hi], 0.22, steel)   # diagonal
    # Ribs over both bays where the arch is high enough to drive under.
    for z in zs[3:-3]:
        for xa, xb in zip(lines[:-1], lines[1:]):
            xm = 0.5 * (xa + xb)
            beam(m, "metal", [xa, top(z), z], [xm, top(z) + 0.9, z], 0.3, steel)
            beam(m, "metal", [xm, top(z) + 0.9, z], [xb, top(z), z], 0.3, steel)
    for z in (-half - 2.0, half + 2.0):
        for x in lines:
            sg.box(m, "concrete", (x - 1.3, deck(z) - 2.0, z - 1.6), (x + 1.3, deck(z) + 6.0, z + 1.6), stone)
    return m


def shell(a, b, h, colour, rings=5, sides=16):
    """One of the two shells of Esplanade - Theatres on the Bay: a low dome of glass under
    pointed aluminium sunshades (the "durian"). Half-axes a (along x) and b, height h; the
    facets stand in for the spikes."""
    m = new_mesh()
    m.anchor(0.0, 0.0)
    col = lin(colour)
    pts = []
    for i in range(rings + 1):
        phi = 0.5 * np.pi * i / rings
        # Odd rings are turned by half a facet: triangles instead of quads, a spikier skin.
        off = 0.5 if i % 2 else 0.0
        ring = []
        for j in range(sides):
            th = 2.0 * np.pi * (j + off) / sides
            bump = 1.0 + (0.035 if (i + j) % 2 else -0.02)
            ring.append(np.array([a * math.cos(phi) * math.cos(th) * bump, h * math.sin(phi) * bump - 0.5,
                                  b * math.cos(phi) * math.sin(th) * bump]))
        pts.append(ring)
    inside = np.array([0.0, 0.0, 0.0])
    for i in range(rings):
        for j in range(sides):
            j1 = (j + 1) % sides
            p, q = pts[i], pts[i + 1]
            if i == rings - 1:
                m.face("metal", [p[j], p[j1], q[0]], None, col, away_from=inside)
                continue
            if i % 2 == 0:
                m.face("metal", [p[j], p[j1], q[j]], None, col, away_from=inside)
                m.face("metal", [p[j1], q[j1], q[j]], None, col, away_from=inside)
            else:
                m.face("metal", [p[j], q[j1], q[j]], None, col, away_from=inside)
                m.face("metal", [p[j], p[j1], q[j1]], None, col, away_from=inside)
    return m


def write_models(lap):
    (FOLDER / "landmarks").mkdir(exist_ok=True)
    marks = []
    near = {e["id"]: e for e in cache_elements("near") if e["t"] != "n"}

    # Pit building: where the map has it, parallel to the pit straight.
    ll = element_ring(near[49890775])
    x, z = lap.to_xz(ll[:, 0], ll[:, 1])
    s, lat = lap.locate(float(x.mean()), float(z.mean()))
    # The map's outline includes the paddock canopies: the front stands 17 m from the middle
    # of the road (pit wall and a pit lane of three lanes), the model is 34 m deep, so its
    # middle (the model origin) is 34 m from the centreline.
    write(pit_building(), "pit_building")
    marks.append({"model": "pit_building", "at": {"s": round(s % lap.length, 1), "side": -1, "dist": 34.0}})

    ids, pts = flyer_parts()
    if len(pts) < 10:
        raise SystemExit("the capsules of the Singapore Flyer were not found in the map cache")
    x, z = lap.to_xz(pts[:, 0], pts[:, 1])
    xz = np.stack([x, z], axis=1)
    hub = xz.mean(axis=0)
    # Direction of the wheel plane: the principal axis of the capsule columns.
    _, _, vt = np.linalg.svd(xz - hub)
    d = vt[0]
    lat_h, lon_h = lap.to_ll(hub[0], hub[1])
    write(flyer(), "flyer")
    # yaw turns the model's -z to (-sin, -cos); its x axis (the wheel plane) to (cos, -sin).
    marks.append({"model": "flyer", "at": {"latlon": [round(float(lat_h), 6), round(float(lon_h), 6)]},
                  "yaw_deg": round(math.degrees(math.atan2(-d[1], d[0])), 1), "y_offset": 0.3})

    ll = element_ring(near[29377119])       # Fullerton Road on the bridge
    x, z = lap.to_xz(ll[:, 0], ll[:, 1])
    ends = sorted(lap.locate(float(a), float(b))[0] for a, b in zip(x, z))
    s_mid, span = 0.5 * (ends[0] + ends[-1]), ends[-1] - ends[0]
    write(anderson_bridge(lap, s_mid, span), "anderson_bridge")
    marks.append({"model": "anderson_bridge", "at": {"s": round(s_mid, 1), "side": 1, "dist": 0.0}})

    # Esplanade: the two shells, on the footprints of the map (their long axes from them).
    for ref, name, height in ((256163011, "esplanade_concert_hall", 30.0), (256163012, "esplanade_theatre", 33.0)):
        ll = element_ring(near[ref])
        x, z = lap.to_xz(ll[:, 0], ll[:, 1])
        xz = np.stack([x, z], axis=1)
        c = 0.5 * (xz.min(axis=0) + xz.max(axis=0))
        _, _, vt = np.linalg.svd(xz - xz.mean(axis=0))
        along = (xz - c) @ vt[0]
        cross = (xz - c) @ vt[1]
        write(shell(0.5 * float(np.ptp(along)), 0.5 * float(np.ptp(cross)), height, DURIAN), name)
        lat_c, lon_c = lap.to_ll(c[0], c[1])
        marks.append({"model": name, "at": {"latlon": [round(float(lat_c), 6), round(float(lon_c), 6)]},
                      "yaw_deg": round(math.degrees(math.atan2(-vt[0][1], vt[0][0])), 1)})

    with open(FOLDER / "landmarks.json", "w", encoding="utf-8") as f:
        f.write("[\n" + ",\n".join(" " + json.dumps(e) for e in marks) + "\n]\n")
    print(f"{FOLDER / 'landmarks.json'}: {len(marks)} landmarks")


if __name__ == "__main__":
    what = sys.argv[1] if len(sys.argv) > 1 else ""
    if what not in ("models", "recipe"):
        raise SystemExit(__doc__)
    os.chdir(ROOT)
    if what == "recipe":
        write_recipe(Lap())
    else:
        write_models(Lap())
