class_name RoadSurface
extends Node3D
## The CAD road of a Track (root of scenes/tracks/rbr_road.tscn, the Track's `Road` slot).
## Visual chunks come from road_mesh.glb (generated by cad/track/road.py); this script adds
## one trimesh StaticBody3D per chunk and material ("tarmac" -> surface "asphalt", "grass"
## -> surface "grass"), built from the very same vertices, so chunks join without gaps.
##
## It also answers exact surface queries from road_profile.json (the banking.py override):
## the road is ruled between the centreline cross-sections, so surface_point() matches the
## mesh to within float error along each cross-section.
## Lateral offsets: + = right of the centreline in race direction. Bank: + = left edge higher.

@export_file("*.json") var profile_path: String = "res://assets/tracks/red_bull_ring/road_profile.json"

var widths: PackedFloat32Array = []
var banks: PackedFloat32Array = []
var verge_left: PackedFloat32Array = []
var verge_right: PackedFloat32Array = []
var racing_line: PackedFloat32Array = []
var chunk_ranges: Array = []          ## [[first_point, last_point], ...] per mesh chunk
var verge_width: float = 30.0
var verge_drop: float = 0.25
var data: TrackData

func _ready() -> void:
	var track := get_parent() as Track
	if track != null:
		data = track.data
	if data == null:
		var t := get_tree().get_first_node_in_group(&"track") as Track
		data = t.data if t != null else null
	_load_profile()
	_build_collision()
	if data != null:
		_configure_materials()

func _load_profile() -> void:
	var f := FileAccess.open(profile_path, FileAccess.READ)
	if f == null:
		push_error("RoadSurface: cannot open %s" % profile_path)
		_fallback_profile()
		return
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if not (parsed is Dictionary) or not (parsed as Dictionary).has("width"):
		push_error("RoadSurface: %s is not a valid road profile (re-run cad/track/road.py)" % profile_path)
		_fallback_profile()
		return
	var d: Dictionary = parsed
	widths = PackedFloat32Array(d["width"])
	banks = PackedFloat32Array(d["bank"])
	verge_left = PackedFloat32Array(d["verge_left"])
	verge_right = PackedFloat32Array(d["verge_right"])
	racing_line = PackedFloat32Array(d["racing_line"])
	chunk_ranges = d.get("chunks", [])
	verge_width = float(d.get("verge_width", 30.0))
	verge_drop = float(d.get("verge_drop", 0.25))
	if data != null and widths.size() != data.points.size():
		push_error("RoadSurface: profile has %d points, track has %d (re-run cad/track/road.py)"
			% [widths.size(), data.points.size()])
		_fallback_profile()

## Queries fall back to the plain track.json cross-section if the profile is unusable.
func _fallback_profile() -> void:
	if data == null:
		return
	widths = data.widths.duplicate()
	banks = PackedFloat32Array()
	banks.resize(widths.size())
	banks.fill(0.0)
	verge_left = banks.duplicate()
	verge_right = banks.duplicate()
	racing_line = banks.duplicate()

## One StaticBody3D per mesh surface, parented to its MeshInstance3D (same local frame).
func _build_collision() -> void:
	for node: Node in find_children("*", "MeshInstance3D", true, false):
		var mi := node as MeshInstance3D
		if mi.mesh == null:
			continue
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF  # flat ground: no shadow pass
		for surf in mi.mesh.get_surface_count():
			var kind := "grass" if _surface_is_grass(mi.mesh, surf) else "asphalt"
			# Single-surface copy (positions + indices only) so the native trimesh builder
			# can be used per surface.
			var src := mi.mesh.surface_get_arrays(surf)
			var arrays := []
			arrays.resize(Mesh.ARRAY_MAX)
			arrays[Mesh.ARRAY_VERTEX] = src[Mesh.ARRAY_VERTEX]
			arrays[Mesh.ARRAY_INDEX] = src[Mesh.ARRAY_INDEX]
			var one := ArrayMesh.new()
			one.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
			var shape := one.create_trimesh_shape()
			var body := StaticBody3D.new()
			body.name = "%s_%s" % [mi.name, kind]
			body.set_meta("surface", kind)
			var cs := CollisionShape3D.new()
			cs.shape = shape
			body.add_child(cs)
			mi.add_child(body)

func _surface_is_grass(mesh: Mesh, surf: int) -> bool:
	var mat := mesh.surface_get_material(surf)
	if mat != null and mat.resource_name == "grass":
		return true
	return mesh is ArrayMesh and (mesh as ArrayMesh).surface_get_name(surf) == "grass"

func _configure_materials() -> void:
	var tarmac := load("res://assets/tracks/red_bull_ring/road_tarmac.tres") as ShaderMaterial
	if tarmac != null:
		tarmac.set_shader_parameter(&"track_length", data.length)
		tarmac.set_shader_parameter(&"start_s", data.start_s)

func _idx(s: float) -> Array:
	var u := data.wrap_s(s) / data.step
	var i := int(floor(u)) % data.points.size()
	return [i, (i + 1) % data.points.size(), u - floor(u)]

func half_width_at(s: float) -> float:
	var r := _idx(s)
	return 0.5 * lerpf(widths[r[0]], widths[r[1]], r[2])

func bank_at(s: float) -> float:
	var r := _idx(s)
	return lerpf(banks[r[0]], banks[r[1]], r[2])

## Verge width (m) on one side at s; side < 0 = left, > 0 = right.
func verge_at(s: float, side: float) -> float:
	var r := _idx(s)
	var a := verge_left if side < 0.0 else verge_right
	return lerpf(a[r[0]], a[r[1]], r[2])

func racing_line_at(s: float) -> float:
	var r := _idx(s)
	return lerpf(racing_line[r[0]], racing_line[r[1]], r[2])

## Exact surface point (road or verge) at s and lateral offset (+ right). Beyond the verge
## the verge plane is extrapolated.
func surface_point(s: float, lateral: float) -> Vector3:
	var r := _idx(s)
	var a := _section_point(r[0], lateral)
	var b := _section_point(r[1], lateral)
	return a.lerp(b, r[2])

## Cross-section frame at centreline point i, as built by cad/track/road.py.
func _section_point(i: int, lateral: float) -> Vector3:
	var n := data.points.size()
	var p := data.points[i]
	var t := (data.points[(i + 1) % n] - data.points[(i - 1 + n) % n]).normalized()
	var rh := t.cross(Vector3.UP).normalized()
	var u0 := rh.cross(t).normalized()
	var bank := banks[i]
	var rb := rh * cos(bank) - u0 * sin(bank)
	var hw := 0.5 * widths[i]
	if absf(lateral) <= hw:
		return p + rb * lateral
	var side := signf(lateral)
	var d := absf(lateral) - hw
	var edge := p + rb * (side * hw)
	return edge + rh * (side * d) + Vector3.DOWN * (verge_drop * d / verge_width)
