class_name RoadSurface
extends Node3D
## The road of a Track (root of scenes/tracks/track_road.tscn, the Track's `Road` slot).
## Everything is loaded from the track folder (Track.dir()):
##   * road_mesh.glb (generated by cad/track/road.py) -> child "RoadMesh". This script adds
##     one trimesh StaticBody3D per chunk and material ("tarmac" -> surface "asphalt",
##     "grass" -> surface "grass"), built from the very same vertices, so chunks join
##     without gaps. Without a GLB the same ribbon (road + grass verges) is built here at
##     runtime from track.json and the profile, so a new track drives before its CAD exists.
##   * road_profile.json (the banking.py override) answers exact surface queries: the road is
##     ruled between the centreline cross-sections, so surface_point() matches the mesh to
##     within float error along each cross-section. Without it the plain track.json
##     cross-section is used (flat, no racing line).
##   * road_tarmac.tres / road_grass.tres: materials of the runtime ribbon (the GLB brings its
##     own); shared defaults live in assets/tracks/_shared.
##   * A lap that crosses itself (a figure of eight) has "bridges" in road_profile.json and a
##     node "bridge_NN" in the GLB (cad/track/bridge.py): the deck that carries the upper
##     road, its side walls and the underpass. `bridges` hands the stretches to the trackside.
## Lateral offsets: + = right of the centreline in race direction. Bank: + = left edge higher.

## Default road materials for tracks whose folder has none (runtime ribbon only).
const SHARED_DIR := "res://assets/tracks/_shared"
const MESH_FILE := "road_mesh.glb"
const PROFILE_FILE := "road_profile.json"
const TARMAC_FILE := "road_tarmac.tres"
const GRASS_FILE := "road_grass.tres"
const RIBBON_CHUNK_POINTS: int = 90     ## runtime ribbon: centreline points per mesh chunk
const RIBBON_VERGE_WIDTH: float = 30.0  ## runtime ribbon without a profile: grass verge width

## Leave empty to use road_profile.json of the track folder.
@export_file("*.json") var profile_path: String = ""

var widths: PackedFloat32Array = []
var banks: PackedFloat32Array = []
var verge_left: PackedFloat32Array = []
var verge_right: PackedFloat32Array = []
var racing_line: PackedFloat32Array = []
var chunk_ranges: Array = []          ## [[first_point, last_point], ...] per mesh chunk
## Crossovers of the lap, from road_profile.json (empty for a lap that does not cross itself):
## [{deck: [s0, s1], upper_window: [s0, s1], lower_window: [s0, s1], parapet_offset,
##   barrier_room, ...}] - see cad/track/bridge.py.
var bridges: Array[Dictionary] = []
## Stretches that are the two carriageways of one road, from road_profile.json (the recipe's
## [[road.pair]], usually none): [{a: [s0, s1], b: [s0, s1], side_a, side_b, gap, separation}],
## side = the side of that stretch the other one is on (-1 left, +1 right) - cad/track/road.py.
var pairs: Array[Dictionary] = []
var verge_width: float = 30.0
var verge_drop: float = 0.25
var data: TrackData
## True when the mesh was built here at runtime (no road_mesh.glb in the track folder).
var is_runtime_mesh: bool = false

var _dir: String = ""

func _ready() -> void:
	var track := get_parent() as Track
	if track == null:
		track = get_tree().get_first_node_in_group(&"track") as Track
	if track != null:
		data = track.data
		_dir = track.dir()
	if profile_path.is_empty() and not _dir.is_empty():
		profile_path = _dir.path_join(PROFILE_FILE)
	_load_profile()
	_load_mesh()
	_build_collision()
	if data != null:
		_configure_materials()

func _load_profile() -> void:
	if profile_path.is_empty() or not FileAccess.file_exists(profile_path):
		_fallback_profile()   # optional file: a track without CAD road data yet
		return
	var f := FileAccess.open(profile_path, FileAccess.READ)
	if f == null:
		push_error("RoadSurface: cannot open %s" % profile_path)
		_fallback_profile()
		return
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if not (parsed is Dictionary) or not (parsed as Dictionary).has("width"):
		push_error("RoadSurface: %s is not a valid road profile (re-run cad/track/road.py)" % profile_path)
		_fallback_profile()
		return
	var d: Dictionary = parsed
	widths = PackedFloat32Array(d["width"])
	var n := widths.size()
	if data != null and n != data.points.size():
		push_error("RoadSurface: profile has %d points, track has %d (re-run cad/track/road.py)"
			% [n, data.points.size()])
		_fallback_profile()
		return
	verge_width = float(d.get("verge_width", 30.0))
	verge_drop = float(d.get("verge_drop", 0.25))
	banks = _profile_array(d, "bank", n, 0.0)
	verge_left = _profile_array(d, "verge_left", n, verge_width)
	verge_right = _profile_array(d, "verge_right", n, verge_width)
	racing_line = _profile_array(d, "racing_line", n, 0.0)
	chunk_ranges = d.get("chunks", [])
	bridges = []
	for b: Variant in d.get("bridges", []):
		if b is Dictionary and (b as Dictionary).has_all(["deck", "upper_window", "lower_window"]):
			bridges.append(b)
	pairs = []
	for p: Variant in d.get("pairs", []):
		if p is Dictionary and (p as Dictionary).has_all(["a", "b", "side_a", "side_b"]):
			pairs.append(p)

## Profile array `key`, or `n` times `fallback` when it is missing or has the wrong size.
static func _profile_array(d: Dictionary, key: String, n: int, fallback: float) -> PackedFloat32Array:
	var a := PackedFloat32Array(d.get(key, []))
	if a.size() != n:
		a.resize(n)
		a.fill(fallback)
	return a

## Without a usable profile, queries use the plain track.json cross-section: flat road, no
## racing line, full verges except on the inside of tight corners (where neighbouring
## cross-sections would fold over each other) and next to another leg of the lap (each leg
## gets half the space between them).
func _fallback_profile() -> void:
	if data == null:
		return
	var n := data.points.size()
	widths = data.widths.duplicate()
	banks = PackedFloat32Array()
	banks.resize(n)
	banks.fill(0.0)
	racing_line = banks.duplicate()
	chunk_ranges = []
	bridges = []
	pairs = []
	verge_width = RIBBON_VERGE_WIDTH
	verge_drop = 0.25
	var lims := TrackGeometry.no_limits(n)
	TrackGeometry.inside_limits(data, lims[0], lims[1])
	TrackGeometry.proximity_limits(data, lims[0], lims[1])
	verge_left = PackedFloat32Array()
	verge_right = PackedFloat32Array()
	verge_left.resize(n)
	verge_right.resize(n)
	for i in n:
		var hw := 0.5 * widths[i]
		verge_left[i] = clampf(lims[0][i] - hw, 0.0, verge_width)
		verge_right[i] = clampf(lims[1][i] - hw, 0.0, verge_width)

## Instances road_mesh.glb of the track folder as "RoadMesh"; without one, builds the ribbon.
func _load_mesh() -> void:
	if get_node_or_null(^"RoadMesh") != null:
		return   # a scene that bakes its own mesh instance
	var glb := _dir.path_join(MESH_FILE)
	if not _dir.is_empty() and ResourceLoader.exists(glb):
		var scene := load(glb) as PackedScene
		if scene != null:
			var inst := scene.instantiate()
			inst.name = "RoadMesh"
			add_child(inst)
			return
		push_error("RoadSurface: cannot load %s" % glb)
	if data != null:
		_build_ribbon()

## Runtime road: the same ruled surface that surface_point() describes, in chunks of
## RIBBON_CHUNK_POINTS cross-sections with a "tarmac" and a "grass" surface each.
## UVs follow cad/track/road.py: UV = (s, lateral m), UV2 = (racing line offset, half width).
func _build_ribbon() -> void:
	is_runtime_mesh = true
	var n := data.points.size()
	var tarmac := _ribbon_material(TARMAC_FILE, "tarmac", Color(0.24, 0.24, 0.25))
	var grass := _ribbon_material(GRASS_FILE, "grass", Color(0.21, 0.36, 0.12))
	var holder := Node3D.new()
	holder.name = "RoadMesh"
	add_child(holder)
	var first := 0
	while first < n:
		var count := mini(RIBBON_CHUNK_POINTS, n - first)
		var road := SurfaceTool.new()
		road.begin(Mesh.PRIMITIVE_TRIANGLES)
		var verge := SurfaceTool.new()
		verge.begin(Mesh.PRIMITIVE_TRIANGLES)
		var verge_quads := 0
		for k in count:
			var i := first + k
			var j := (i + 1) % n
			var s0 := i * data.step
			var s1 := s0 + data.step if j != 0 else data.length
			var lat_i := _ribbon_laterals(i)
			var lat_j := _ribbon_laterals(j)
			for c in 3:   # strips: left verge, road, right verge
				if c != 1 and maxf(absf(lat_i[c + 1] - lat_i[c]), absf(lat_j[c + 1] - lat_j[c])) < 0.05:
					continue
				verge_quads += 0 if c == 1 else 1
				_ribbon_quad(road if c == 1 else verge, i, j, s0, s1,
						lat_i[c], lat_i[c + 1], lat_j[c], lat_j[c + 1])
		var mesh := ArrayMesh.new()
		road.index()
		road.commit(mesh)
		mesh.surface_set_name(0, "tarmac")
		mesh.surface_set_material(0, tarmac)
		if verge_quads > 0:
			verge.index()
			verge.commit(mesh)
			mesh.surface_set_name(1, "grass")
			mesh.surface_set_material(1, grass)
		var mi := MeshInstance3D.new()
		mi.name = "Chunk_%02d" % (first / RIBBON_CHUNK_POINTS)
		mi.mesh = mesh
		holder.add_child(mi)
		first += count

## Lateral offsets of the four ribbon columns at point i: verge end, edge, edge, verge end.
func _ribbon_laterals(i: int) -> Array[float]:
	var hw := 0.5 * widths[i]
	return [-hw - verge_left[i], -hw, hw, hw + verge_right[i]]

## One ribbon cell between cross-sections i (laterals a0..b0) and j (a1..b1), facing up.
func _ribbon_quad(st: SurfaceTool, i: int, j: int, s0: float, s1: float,
		a0: float, b0: float, a1: float, b1: float) -> void:
	var corners := [[i, s0, a0], [j, s1, a1], [i, s0, b0], [i, s0, b0], [j, s1, a1], [j, s1, b1]]
	for c: Array in corners:
		var p: int = c[0]
		var lat: float = c[2]
		st.set_normal(_section_up(p))
		st.set_uv(Vector2(c[1], lat))
		st.set_uv2(Vector2(racing_line[p], 0.5 * widths[p]))
		st.add_vertex(_section_point(p, lat))

## Material `file` of the track folder, else a private copy of the shared default, else a
## plain colour. `mat_name` is what _surface_is_grass() looks at.
func _ribbon_material(file: String, mat_name: String, colour: Color) -> Material:
	var own := _dir.path_join(file)
	if not _dir.is_empty() and ResourceLoader.exists(own):
		return load(own) as Material
	var shared := SHARED_DIR.path_join(file)
	if ResourceLoader.exists(shared):
		# A copy: _configure_materials() writes this track's length into the tarmac shader.
		var m := (load(shared) as Material).duplicate() as Material
		m.resource_name = mat_name
		return m
	var std := StandardMaterial3D.new()
	std.resource_name = mat_name
	std.albedo_color = colour
	std.roughness = 0.9
	return std

## One StaticBody3D per mesh surface, parented to its MeshInstance3D (same local frame).
func _build_collision() -> void:
	for node: Node in find_children("*", "MeshInstance3D", true, false):
		var mi := node as MeshInstance3D
		if mi.mesh == null:
			continue
		# Flat ground: no shadow pass. A bridge shades the road under it (its faces are
		# one-sided, so both sides cast).
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_DOUBLE_SIDED if _is_bridge(mi) \
				else GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		for surf in mi.mesh.get_surface_count():
			var kind := "grass" if _surface_is_grass(mi.mesh, surf) else "asphalt"
			# Single-surface copy (positions + indices only) so the native trimesh builder
			# can be used per surface.
			var src := mi.mesh.surface_get_arrays(surf)
			var arrays := []
			arrays.resize(Mesh.ARRAY_MAX)
			arrays[Mesh.ARRAY_VERTEX] = src[Mesh.ARRAY_VERTEX]
			arrays[Mesh.ARRAY_INDEX] = src[Mesh.ARRAY_INDEX]
			var one := ArrayMesh.new()
			one.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
			var shape := one.create_trimesh_shape()
			var body := StaticBody3D.new()
			body.name = "%s_%s" % [mi.name, kind]
			body.set_meta("surface", kind)
			var cs := CollisionShape3D.new()
			cs.shape = shape
			body.add_child(cs)
			mi.add_child(body)

## True for the "bridge_NN" nodes of the GLB (the import may append a suffix to the name).
static func _is_bridge(mi: MeshInstance3D) -> bool:
	return String(mi.name).begins_with("bridge_")

## True when s is on the deck of a bridge (the upper road of a crossover).
func on_bridge(s: float) -> bool:
	for b in bridges:
		if s_in_range(s, b["deck"]):
			return true
	return false

## True when s lies in [range[0], range[1]] along the lap (the range may wrap the finish line).
func s_in_range(s: float, r: Array) -> bool:
	var a := float(r[0])
	return fposmod(s - a, data.length) <= fposmod(float(r[1]) - a, data.length)

func _surface_is_grass(mesh: Mesh, surf: int) -> bool:
	var mat := mesh.surface_get_material(surf)
	if mat != null and mat.resource_name == "grass":
		return true
	return mesh is ArrayMesh and (mesh as ArrayMesh).surface_get_name(surf) == "grass"

## The tarmac shader paints the finish line and the grid from the lap length and start_s.
func _configure_materials() -> void:
	var seen := {}
	for node: Node in find_children("*", "MeshInstance3D", true, false):
		var mesh := (node as MeshInstance3D).mesh
		if mesh == null:
			continue
		for surf in mesh.get_surface_count():
			var mat := mesh.surface_get_material(surf) as ShaderMaterial
			if mat == null or seen.has(mat) or _surface_is_grass(mesh, surf):
				continue
			seen[mat] = true
			mat.set_shader_parameter(&"track_length", data.length)
			mat.set_shader_parameter(&"start_s", data.start_s)

func _idx(s: float) -> Array:
	var u := data.wrap_s(s) / data.step
	var i := int(floor(u)) % data.points.size()
	return [i, (i + 1) % data.points.size(), u - floor(u)]

func half_width_at(s: float) -> float:
	var r := _idx(s)
	return 0.5 * lerpf(widths[r[0]], widths[r[1]], r[2])

func bank_at(s: float) -> float:
	var r := _idx(s)
	return lerpf(banks[r[0]], banks[r[1]], r[2])

## Verge width (m) on one side at s; side < 0 = left, > 0 = right.
func verge_at(s: float, side: float) -> float:
	var r := _idx(s)
	var a := verge_left if side < 0.0 else verge_right
	return lerpf(a[r[0]], a[r[1]], r[2])

func racing_line_at(s: float) -> float:
	var r := _idx(s)
	return lerpf(racing_line[r[0]], racing_line[r[1]], r[2])

## Exact surface point (road or verge) at s and lateral offset (+ right). Beyond the verge
## the verge plane is extrapolated.
func surface_point(s: float, lateral: float) -> Vector3:
	var r := _idx(s)
	var a := _section_point(r[0], lateral)
	var b := _section_point(r[1], lateral)
	return a.lerp(b, r[2])

## Cross-section frame at centreline point i, as built by cad/track/road.py.
func _section_point(i: int, lateral: float) -> Vector3:
	var n := data.points.size()
	var p := data.points[i]
	var t := (data.points[(i + 1) % n] - data.points[(i - 1 + n) % n]).normalized()
	var rh := t.cross(Vector3.UP).normalized()
	var u0 := rh.cross(t).normalized()
	var bank := banks[i]
	var rb := rh * cos(bank) - u0 * sin(bank)
	var hw := 0.5 * widths[i]
	if absf(lateral) <= hw:
		return p + rb * lateral
	var side := signf(lateral)
	var d := absf(lateral) - hw
	var edge := p + rb * (side * hw)
	return edge + rh * (side * d) + Vector3.DOWN * (verge_drop * d / verge_width)

## Road normal of the cross-section at centreline point i.
func _section_up(i: int) -> Vector3:
	var n := data.points.size()
	var t := (data.points[(i + 1) % n] - data.points[(i - 1 + n) % n]).normalized()
	var rh := t.cross(Vector3.UP).normalized()
	var u0 := rh.cross(t).normalized()
	return u0 * cos(banks[i]) + rh * sin(banks[i])
